changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Frontend Changes
      labels:
        - frontend
    - title: Backend Changes
      labels:
        - backend
    - title: Lambda Changes
      labels:
        - lambda
    - title: Other Changes
      labels:
        - "*"