version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build -- -c=$stage
      - aws s3 sync --delete 'dist/upgrade/' s3://$bucket_name --cache-control max-age=3600
  post_build:
    commands:
      - echo 'Invalidating distribuition cache'
      - aws cloudfront create-invalidation --distribution-id $distribuition_id --paths "/*"
