version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 10
  pre_build:
    commands:
      - echo installing node packages
      - npm run install:all
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=656500730782.dkr.ecr.us-east-1.amazonaws.com/ees-backend
      - IMAGE_TAG=$ENVIRONMENT
  build:
    commands:
      - echo Build started on `date`
      - echo deploying serverless functions
      - npm run deploy:schedule -- --stage=$IMAGE_TAG
      - echo Building docker config
      - npm run dockerConfig:$IMAGE_TAG
      - echo Building the Docker image...
      - docker build --build-arg ENVIRONMENT=$IMAGE_TAG -t $REPOSITORY_URI:latest .

      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
    - Dockerrun.aws.json
  discard-paths: yes
