services:
  upgrade-app:
    build:
      context: .
      dockerfile: ./dev.singleContainerApp.Dockerfile
    image: upgrade-app:latest
    user: "node"
    env_file:
      - ./backend/packages/Upgrade/.env.docker.local
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/src/app/frontend
      - ./backend:/usr/src/app/backend
      - /usr/src/app/frontend/node_modules
    tmpfs:
      - /usr/src/app/frontend/node_modules/@rollup # Exclude @rollup from host mount
    networks:
      - localdev
    ports:
      - "4200:4200"
      - "3030:3030"
    depends_on:
      - "postgres"

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - localdev
    ports:
      - "5432:5432"
    volumes:
      - upgradedbdata:/var/lib/postgresql/data
  
volumes:
  upgradedbdata:

networks:
  localdev:
    driver: "bridge"