// HTML Reporter for Node QuickTest
// Captures test output and generates an HTML file that can be opened in a browser

import * as fs from 'fs';
import * as path from 'path';
import { exec } from 'child_process';

interface LogEntry {
  message: string;
  type: 'log' | 'header' | 'error' | 'success';
}

class HTMLReporter {
  private logs: LogEntry[] = [];
  private statusMessage = 'Running tests...';
  private statusType: 'running' | 'success' | 'error' = 'running';

  log(message: string, type: 'log' | 'header' | 'error' | 'success' = 'log'): void {
    this.logs.push({ message, type });
    console.log(message); // Also log to console
  }

  updateStatus(message: string, type: 'running' | 'success' | 'error' = 'running'): void {
    this.statusMessage = message;
    this.statusType = type;
  }

  generateHTML(): string {
    const logEntries = this.logs
      .map((entry) => {
        let className = 'log-entry';
        if (entry.type === 'header') className += ' log-header';
        else if (entry.type === 'error') className += ' log-error';
        else if (entry.type === 'success') className += ' log-success';

        // Escape HTML special characters
        const escapedMessage = entry.message
          .replace(/&/g, '&amp;')
          .replace(/</g, '&lt;')
          .replace(/>/g, '&gt;')
          .replace(/"/g, '&quot;')
          .replace(/'/g, '&#039;');

        return `        <div class="${className}">${escapedMessage}</div>`;
      })
      .join('\n');

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UpGrade Client - Node QuickTest</title>
    <link rel="stylesheet" href="../shared/shared-styles.css">
</head>
<body>
    <h1 class="node">UpGrade Client - Node QuickTest</h1>
    <div class="info">
        <strong>Version:</strong> Node.js (TypeScript)<br>
        <strong>Location:</strong> quicktest/node/<br>
        <strong>Note:</strong> This output was generated by running the Node.js test and capturing all logs.
    </div>

    <div id="status" class="status ${this.statusType}">
        ${this.statusMessage}
    </div>

    <div id="output" class="output">
${logEntries}
    </div>
</body>
</html>
`;
  }

  async writeAndOpen(): Promise<void> {
    const outputPath = path.join(__dirname, 'test-results.html');
    const html = this.generateHTML();

    // Write the HTML file
    fs.writeFileSync(outputPath, html, 'utf8');
    console.log(`\nHTML report generated: ${outputPath}`);

    // Open in default browser (platform-specific)
    const openCommand =
      process.platform === 'darwin' ? 'open' : process.platform === 'win32' ? 'start' : 'xdg-open';

    exec(`${openCommand} "${outputPath}"`, (error) => {
      if (error) {
        console.error('Failed to open browser:', error);
      } else {
        console.log('Opening browser...');
      }
    });
  }
}

// Create a singleton reporter instance
export const reporter = new HTMLReporter();

// Export logger functions that use the reporter
export function logToHTML(message: string, type: 'log' | 'header' | 'error' | 'success' = 'log'): void {
  reporter.log(message, type);
}

export function updateStatusHTML(message: string, type: 'running' | 'success' | 'error' = 'running'): void {
  reporter.updateStatus(message, type);
}

export async function finalizeAndOpenHTML(): Promise<void> {
  await reporter.writeAndOpen();
}
