import { MigrationInterface, QueryRunner } from "typeorm";

export class MoocletPolicySupport1730483326950 implements MigrationInterface {
    name = 'MoocletPolicySupport1730483326950'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "decision_point" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" uuid NOT NULL, "twoCharacterId" character(2) NOT NULL, "site" character varying NOT NULL, "target" character varying, "description" character varying NOT NULL, "order" integer, "excludeIfReached" boolean NOT NULL DEFAULT false, "experimentId" uuid, CONSTRAINT "PK_e55e73f039848e3a1cac0e491bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."condition_payload_payloadtype_enum" AS ENUM('string', 'json', 'csv')`);
        await queryRunner.query(`CREATE TABLE "condition_payload" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" uuid NOT NULL, "payloadValue" character varying NOT NULL, "payloadType" "public"."condition_payload_payloadtype_enum" NOT NULL DEFAULT 'string', "parentConditionId" uuid, "decisionPointId" uuid, CONSTRAINT "PK_64bdd8ec11321806973e7d627ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "factor" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" uuid NOT NULL, "name" character varying NOT NULL, "order" integer, "description" character varying, "experimentId" uuid, CONSTRAINT "PK_474c0e9d4ca1c181f178952187d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."level_payloadtype_enum" AS ENUM('string', 'json', 'csv')`);
        await queryRunner.query(`CREATE TABLE "level" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying, "payloadValue" character varying, "payloadType" "public"."level_payloadtype_enum" NOT NULL DEFAULT 'string', "order" integer, "factorId" uuid, CONSTRAINT "PK_d3f1a7a6f09f1c3144bacdc6bcc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "level_combination_element" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" uuid NOT NULL, "conditionId" uuid, "levelId" uuid, CONSTRAINT "PK_dc280a2be086193e0bc06cd88fa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "experiment_condition" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" uuid NOT NULL, "twoCharacterId" character(2) NOT NULL, "name" character varying, "description" character varying, "conditionCode" character varying, "assignmentWeight" real NOT NULL, "order" integer, "experimentId" uuid, CONSTRAINT "PK_5bdfd20bb9ace3415008c296fff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."state_time_log_fromstate_enum" AS ENUM('inactive', 'preview', 'scheduled', 'enrolling', 'enrollmentComplete', 'cancelled', 'archived')`);
        await queryRunner.query(`CREATE TYPE "public"."state_time_log_tostate_enum" AS ENUM('inactive', 'preview', 'scheduled', 'enrolling', 'enrollmentComplete', 'cancelled', 'archived')`);
        await queryRunner.query(`CREATE TABLE "state_time_log" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" uuid NOT NULL, "fromState" "public"."state_time_log_fromstate_enum" NOT NULL, "toState" "public"."state_time_log_tostate_enum" NOT NULL, "timeLog" TIMESTAMP NOT NULL, "experimentId" uuid, CONSTRAINT "PK_760d29f7bfded82e5b51cfabb26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "experiment_segment_exclusion" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "segmentId" uuid NOT NULL, "experimentId" uuid NOT NULL, CONSTRAINT "PK_54747bc2fc0d9a509f551371b60" PRIMARY KEY ("segmentId", "experimentId"))`);
        await queryRunner.query(`CREATE TABLE "group_for_segment" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "segmentId" uuid NOT NULL, "groupId" character varying NOT NULL, "type" character varying NOT NULL, CONSTRAINT "PK_831eaa3563190f840db9ebe4f95" PRIMARY KEY ("segmentId", "groupId", "type"))`);
        await queryRunner.query(`CREATE TABLE "individual_for_segment" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "segmentId" uuid NOT NULL, "userId" character varying NOT NULL, CONSTRAINT "PK_0a965e751d45b5921549274a65c" PRIMARY KEY ("segmentId", "userId"))`);
        await queryRunner.query(`CREATE TABLE "feature_flag_segment_exclusion" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "segmentId" uuid NOT NULL, "featureFlagId" uuid NOT NULL, "enabled" boolean NOT NULL DEFAULT false, "listType" character varying NOT NULL, CONSTRAINT "PK_b81176ab3b0e31527d7cc23db78" PRIMARY KEY ("segmentId", "featureFlagId"))`);
        await queryRunner.query(`CREATE TABLE "feature_flag_exposure" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "featureFlagId" uuid NOT NULL, "experimentUserId" character varying NOT NULL, CONSTRAINT "PK_99ab312ceb343f3121eeadb2d50" PRIMARY KEY ("featureFlagId", "experimentUserId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6908f3ead6dd3a6fd4ce38514e" ON "feature_flag_exposure" ("featureFlagId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6cefc76de0ca7c9a38faae5a8c" ON "feature_flag_exposure" ("experimentUserId") `);
        await queryRunner.query(`CREATE TYPE "public"."feature_flag_status_enum" AS ENUM('enabled', 'disabled', 'archived')`);
        await queryRunner.query(`CREATE TYPE "public"."feature_flag_filtermode_enum" AS ENUM('includeAll', 'excludeAll')`);
        await queryRunner.query(`CREATE TABLE "feature_flag" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" uuid NOT NULL, "name" character varying NOT NULL, "key" text NOT NULL, "description" character varying NOT NULL, "context" text array NOT NULL, "tags" text array, "status" "public"."feature_flag_status_enum" NOT NULL DEFAULT 'disabled', "filterMode" "public"."feature_flag_filtermode_enum" NOT NULL DEFAULT 'excludeAll', CONSTRAINT "UQ_653d98ebae725596b4052f80a65" UNIQUE ("key", "context"), CONSTRAINT "PK_f390205410d884907604a90c0f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "feature_flag_segment_inclusion" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "segmentId" uuid NOT NULL, "featureFlagId" uuid NOT NULL, "enabled" boolean NOT NULL DEFAULT false, "listType" character varying NOT NULL, CONSTRAINT "PK_c1d54498ada310a4d93e9b158d2" PRIMARY KEY ("segmentId", "featureFlagId"))`);
        await queryRunner.query(`CREATE TYPE "public"."segment_type_enum" AS ENUM('public', 'private', 'global_exclude')`);
        await queryRunner.query(`CREATE TABLE "segment" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying, "context" character varying NOT NULL, "type" "public"."segment_type_enum" NOT NULL DEFAULT 'public', CONSTRAINT "PK_d648ac58d8e0532689dfb8ad7ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "experiment_segment_inclusion" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "segmentId" uuid NOT NULL, "experimentId" uuid NOT NULL, CONSTRAINT "PK_b3f79c9b9aae99668e0c9860b97" PRIMARY KEY ("segmentId", "experimentId"))`);
        await queryRunner.query(`CREATE TABLE "stratification_factor" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "stratificationFactorName" character varying NOT NULL, CONSTRAINT "PK_9ebfa233a2cbd8a560ca15f3f54" PRIMARY KEY ("stratificationFactorName"))`);
        await queryRunner.query(`CREATE TYPE "public"."experiment_state_enum" AS ENUM('inactive', 'preview', 'scheduled', 'enrolling', 'enrollmentComplete', 'cancelled', 'archived')`);
        await queryRunner.query(`CREATE TYPE "public"."experiment_consistencyrule_enum" AS ENUM('individual', 'experiment', 'group')`);
        await queryRunner.query(`CREATE TYPE "public"."experiment_assignmentunit_enum" AS ENUM('individual', 'group', 'within-subjects')`);
        await queryRunner.query(`CREATE TYPE "public"."experiment_postexperimentrule_enum" AS ENUM('continue', 'revert', 'assign')`);
        await queryRunner.query(`CREATE TYPE "public"."experiment_conditionorder_enum" AS ENUM('random', 'random round robin', 'ordered round robin')`);
        await queryRunner.query(`CREATE TYPE "public"."experiment_assignmentalgorithm_enum" AS ENUM('random', 'stratified random sampling')`);
        await queryRunner.query(`CREATE TYPE "public"."experiment_filtermode_enum" AS ENUM('includeAll', 'excludeAll')`);
        await queryRunner.query(`CREATE TYPE "public"."experiment_type_enum" AS ENUM('Simple', 'Factorial')`);
        await queryRunner.query(`CREATE TABLE "experiment" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "context" text array NOT NULL, "state" "public"."experiment_state_enum" NOT NULL DEFAULT 'inactive', "startOn" TIMESTAMP, "consistencyRule" "public"."experiment_consistencyrule_enum", "assignmentUnit" "public"."experiment_assignmentunit_enum" NOT NULL, "postExperimentRule" "public"."experiment_postexperimentrule_enum" NOT NULL, "enrollmentCompleteCondition" json, "endOn" TIMESTAMP, "revertTo" uuid, "tags" text array, "group" text, "conditionOrder" "public"."experiment_conditionorder_enum", "assignmentAlgorithm" "public"."experiment_assignmentalgorithm_enum" NOT NULL DEFAULT 'random', "logging" boolean NOT NULL DEFAULT false, "filterMode" "public"."experiment_filtermode_enum" NOT NULL DEFAULT 'excludeAll', "backendVersion" character varying NOT NULL DEFAULT '1.0.0', "type" "public"."experiment_type_enum" NOT NULL DEFAULT 'Simple', "stratificationFactorStratificationFactorName" character varying, CONSTRAINT "PK_4f6eec215c62eec1e0fde987caf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "archived_stats" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" uuid NOT NULL, "result" jsonb NOT NULL, "queryId" uuid, CONSTRAINT "REL_df18fe5ea7298a1dc7bfb33b06" UNIQUE ("queryId"), CONSTRAINT "PK_afc8a335c8d9d48cefaf1aa2c09" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."query_repeatedmeasure_enum" AS ENUM('MEAN', 'EARLIEST', 'MOST RECENT', 'COUNT', 'PERCENTAGE')`);
        await queryRunner.query(`CREATE TABLE "query" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" uuid NOT NULL, "name" text NOT NULL, "query" jsonb NOT NULL, "repeatedMeasure" "public"."query_repeatedmeasure_enum" NOT NULL DEFAULT 'MOST RECENT', "metricKey" character varying, "experimentId" uuid, CONSTRAINT "PK_be23114e9d505264e2fdd227537" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."metric_type_enum" AS ENUM('continuous', 'categorical')`);
        await queryRunner.query(`CREATE TABLE "metric" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "key" character varying NOT NULL, "type" "public"."metric_type_enum" NOT NULL DEFAULT 'continuous', "allowedData" text, "context" text array, CONSTRAINT "PK_612a9a5fc23f3e2a9473b21d23c" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "log" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" SERIAL NOT NULL, "uniquifier" character varying NOT NULL DEFAULT '1', "timeStamp" TIMESTAMP NOT NULL DEFAULT now(), "data" jsonb NOT NULL, "userId" character varying, CONSTRAINT "PK_350604cbdf991d5930d9e618fbd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cea2ed3a494729d4b21edbd298" ON "log" ("userId") `);
        await queryRunner.query(`CREATE TABLE "experiment_user" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" character varying NOT NULL, "group" json, "workingGroup" json, "originalUserId" character varying, CONSTRAINT "PK_bb6db004eeb82db68de9225e877" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_stratification_factor" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "userId" character varying NOT NULL, "factorName" character varying NOT NULL, "stratificationFactorValue" character varying NOT NULL, CONSTRAINT "PK_17c5f1a852052b6800e15febbd6" PRIMARY KEY ("userId", "factorName"))`);
        await queryRunner.query(`CREATE TYPE "public"."experiment_audit_log_type_enum" AS ENUM('experimentCreated', 'experimentUpdated', 'experimentStateChanged', 'experimentDeleted', 'experimentDataExported', 'experimentDesignExported', 'featureFlagCreated', 'featureFlagUpdated', 'featureFlagStatusChanged', 'featureFlagDeleted', 'featureFlagDataExported', 'featureFlagDesignExported')`);
        await queryRunner.query(`CREATE TABLE "experiment_audit_log" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."experiment_audit_log_type_enum" NOT NULL, "data" json NOT NULL, "userEmail" character varying, CONSTRAINT "PK_6d096ff1d454e4d5718e7eceb8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('admin', 'creator', 'user manager', 'reader')`);
        await queryRunner.query(`CREATE TABLE "user" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "email" character varying NOT NULL, "firstName" character varying, "lastName" character varying, "role" "public"."user_role_enum" DEFAULT 'reader', "imageUrl" character varying, "localTimeZone" character varying, CONSTRAINT "PK_e12875dfb3b1d92d7d7c5377e22" PRIMARY KEY ("email"))`);
        await queryRunner.query(`CREATE TABLE "setting" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" SERIAL NOT NULL, "toCheckAuth" boolean NOT NULL, "toFilterMetric" boolean NOT NULL, CONSTRAINT "PK_fcb21187dc6094e24a48f677bed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scheduled_job" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" character varying NOT NULL, "type" character varying NOT NULL, "timeStamp" TIMESTAMP NOT NULL, "executionArn" character varying NOT NULL, "experimentId" uuid, CONSTRAINT "PK_893185383f029ca8d57bb781fa8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "explicit_individual_assignment" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" uuid NOT NULL, "previewUserId" character varying, "experimentId" uuid, "experimentConditionId" uuid, CONSTRAINT "PK_3d547feb84178609965e5f14ef0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_502b25664bcdd4b6721122faf0" ON "explicit_individual_assignment" ("experimentId") `);
        await queryRunner.query(`CREATE TABLE "preview_user" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" character varying NOT NULL, CONSTRAINT "PK_30ce3f8f1211bc659b595edd175" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."mooclet_policy_support_policy_name_enum" AS ENUM('ts_configurable')`);
        await queryRunner.query(`CREATE TABLE "mooclet_policy_support" ("id" uuid NOT NULL, "policy_name" "public"."mooclet_policy_support_policy_name_enum" NOT NULL, "policy_paramater_schema" jsonb NOT NULL, CONSTRAINT "PK_46d006de5d6271bcdc9fa378d7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "monitored_decision_point" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" uuid NOT NULL, "site" character varying NOT NULL, "target" character varying, "experimentId" character varying, "condition" character varying, "userId" character varying, CONSTRAINT "PK_7fd52382a1b12f6d55ec2cc674d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c8f3c5d7e18ba5b504b91d96c2" ON "monitored_decision_point" ("site") `);
        await queryRunner.query(`CREATE INDEX "IDX_400734a43360ef813c6080ddbb" ON "monitored_decision_point" ("target") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ac3dba0b5e060528dbdc34b51" ON "monitored_decision_point" ("experimentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_be1ade8096668d342a8d37e812" ON "monitored_decision_point" ("userId") `);
        await queryRunner.query(`CREATE TABLE "monitored_decision_point_log" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" SERIAL NOT NULL, "condition" character varying, "uniquifier" character varying, "monitoredDecisionPointId" uuid, CONSTRAINT "PK_2fa4825c93a748b4e62553a46fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4e9bf07b07327c60523614ceed" ON "monitored_decision_point_log" ("monitoredDecisionPointId") `);
        await queryRunner.query(`CREATE TYPE "public"."individual_exclusion_exclusioncode_enum" AS ENUM('participant reached experiment prior to experiment enrolling', 'participant reached experiment during enrollment complete', 'participant was on the exclusion list', 'participant’s group was on the exclusion list', 'participant excluded due to group assignment logic', 'participant excluded due to incomplete group information', 'participant''s group or working group is incorrect', 'participant is excluded by client', 'participant excluded due to unspecified error')`);
        await queryRunner.query(`CREATE TABLE "individual_exclusion" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" character varying NOT NULL, "exclusionCode" "public"."individual_exclusion_exclusioncode_enum", "experimentId" uuid, "userId" character varying, CONSTRAINT "PK_2084e00363f40f96ce81ad788b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_43238be19de9500c290393b907" ON "individual_exclusion" ("experimentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_de26ba8251f4ebf8b9c8ccf623" ON "individual_exclusion" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."individual_enrollment_enrollmentcode_enum" AS ENUM('participant enrolled via algorithm', 'participant enrolled due to group enrollment')`);
        await queryRunner.query(`CREATE TABLE "individual_enrollment" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" character varying NOT NULL, "groupId" character varying, "enrollmentCode" "public"."individual_enrollment_enrollmentcode_enum", "experimentId" uuid, "partitionId" uuid, "userId" character varying, "conditionId" uuid, CONSTRAINT "PK_51a228f5bfaf0961e1e33ba1fdb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6bc8c85db258f328c7af93346e" ON "individual_enrollment" ("experimentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6b061b4c2e9cf33b19aea73e7" ON "individual_enrollment" ("partitionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b4575e2a0c125578c9744492c7" ON "individual_enrollment" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4f4d2f2ec491226d4692ed400f" ON "individual_enrollment" ("conditionId") `);
        await queryRunner.query(`CREATE TYPE "public"."group_exclusion_exclusioncode_enum" AS ENUM('participant reached experiment prior to experiment enrolling', 'participant reached experiment during enrollment complete', 'participant was on the exclusion list', 'participant’s group was on the exclusion list', 'participant excluded due to group assignment logic', 'participant excluded due to incomplete group information', 'participant''s group or working group is incorrect', 'participant is excluded by client', 'participant excluded due to unspecified error')`);
        await queryRunner.query(`CREATE TABLE "group_exclusion" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" character varying NOT NULL, "exclusionCode" "public"."group_exclusion_exclusioncode_enum", "groupId" character varying NOT NULL, "experimentId" uuid, CONSTRAINT "PK_eab94b00f9762d7484c606840e0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_15ae48e288f94c0aab841cd807" ON "group_exclusion" ("experimentId") `);
        await queryRunner.query(`CREATE TABLE "group_enrollment" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" character varying NOT NULL, "groupId" character varying NOT NULL, "experimentId" uuid, "partitionId" uuid, "conditionId" uuid, CONSTRAINT "PK_3d773718f69fca13135f2ab4769" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ae99aafabd65ee3251d59e1f5b" ON "group_enrollment" ("experimentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_151c40ca733232929477532903" ON "group_enrollment" ("partitionId") `);
        await queryRunner.query(`CREATE TYPE "public"."experiment_error_type_enum" AS ENUM('Database not reachable', 'Database auth fail', 'Error in the assignment algorithm', 'Parameter missing in the client request', 'Parameter not in the correct format', 'User ID not found', 'Query Failed', 'Error reported from client', 'Experiment user not defined', 'Experiment user group not defined', 'Working group is not a subset of user group', 'Invalid token', 'Token is not present in request', 'JWT Token validation failed', 'Error in migration', 'Email send error', 'Condition not found', 'Experiment ID not provided for shared Decision Point', 'Experiment ID provided is invalid for shared Decision Point', 'Caliper profile or event not supported', 'Feature Flag with same key already exists for this app-context', 'Missing \`User-Id\` header')`);
        await queryRunner.query(`CREATE TABLE "experiment_error" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "versionNumber" integer NOT NULL, "id" SERIAL NOT NULL, "endPoint" character varying, "errorCode" integer, "message" character varying, "name" character varying, "type" "public"."experiment_error_type_enum" NOT NULL, CONSTRAINT "PK_92bb406901d75dd0de5cf119ed2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "segment_for_segment" ("childSegmentId" uuid NOT NULL, "parentSegmentId" uuid NOT NULL, CONSTRAINT "PK_e4606af021f20ee98736d83d2fa" PRIMARY KEY ("childSegmentId", "parentSegmentId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7cbe54e77df890c36415493e98" ON "segment_for_segment" ("childSegmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb101a942537f1fc0a7ef7994c" ON "segment_for_segment" ("parentSegmentId") `);
        await queryRunner.query(`CREATE TABLE "metric_log" ("metricKey" character varying NOT NULL, "logId" integer NOT NULL, CONSTRAINT "PK_ebb632fa6382d423de632631326" PRIMARY KEY ("metricKey", "logId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_81c6609c523e34b8f001cad717" ON "metric_log" ("metricKey") `);
        await queryRunner.query(`CREATE INDEX "IDX_c022cd84fd9fa789cbaee40b41" ON "metric_log" ("logId") `);
        await queryRunner.query(`ALTER TABLE "decision_point" ADD CONSTRAINT "FK_a12b2ac5e10ea27d692b43fd80c" FOREIGN KEY ("experimentId") REFERENCES "experiment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "condition_payload" ADD CONSTRAINT "FK_1b19d3c212f0314144de579a120" FOREIGN KEY ("parentConditionId") REFERENCES "experiment_condition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "condition_payload" ADD CONSTRAINT "FK_017f4e5a324cb198939fff2af8c" FOREIGN KEY ("decisionPointId") REFERENCES "decision_point"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "factor" ADD CONSTRAINT "FK_2dba7d958204335092fdfb5b337" FOREIGN KEY ("experimentId") REFERENCES "experiment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "level" ADD CONSTRAINT "FK_0d95bcd7511d345903a8c6b8481" FOREIGN KEY ("factorId") REFERENCES "factor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "level_combination_element" ADD CONSTRAINT "FK_6884570d63bde354d65406ceb3f" FOREIGN KEY ("conditionId") REFERENCES "experiment_condition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "level_combination_element" ADD CONSTRAINT "FK_ecec1a2e76e475ee9f4c14ad94e" FOREIGN KEY ("levelId") REFERENCES "level"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_condition" ADD CONSTRAINT "FK_390a67a227a832e28d48d33607e" FOREIGN KEY ("experimentId") REFERENCES "experiment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "state_time_log" ADD CONSTRAINT "FK_aa0df63ad4adcf2e827eaad3338" FOREIGN KEY ("experimentId") REFERENCES "experiment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_segment_exclusion" ADD CONSTRAINT "FK_915022e01487b0245a16cbc55f3" FOREIGN KEY ("segmentId") REFERENCES "segment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_segment_exclusion" ADD CONSTRAINT "FK_7d22a811ae04d2ed1b8af0e9c05" FOREIGN KEY ("experimentId") REFERENCES "experiment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_for_segment" ADD CONSTRAINT "FK_715bbd2f483a715789a991123eb" FOREIGN KEY ("segmentId") REFERENCES "segment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "individual_for_segment" ADD CONSTRAINT "FK_cb84433b17891682f9a77126754" FOREIGN KEY ("segmentId") REFERENCES "segment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature_flag_segment_exclusion" ADD CONSTRAINT "FK_b592d039e8ae2eed7a00c89cab0" FOREIGN KEY ("segmentId") REFERENCES "segment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature_flag_segment_exclusion" ADD CONSTRAINT "FK_d45d8b0089b0965c79b57fe84e7" FOREIGN KEY ("featureFlagId") REFERENCES "feature_flag"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature_flag_exposure" ADD CONSTRAINT "FK_6908f3ead6dd3a6fd4ce38514e6" FOREIGN KEY ("featureFlagId") REFERENCES "feature_flag"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature_flag_exposure" ADD CONSTRAINT "FK_6cefc76de0ca7c9a38faae5a8c4" FOREIGN KEY ("experimentUserId") REFERENCES "experiment_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature_flag_segment_inclusion" ADD CONSTRAINT "FK_e0abd5d8d0200b9e4d2fecf139e" FOREIGN KEY ("segmentId") REFERENCES "segment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature_flag_segment_inclusion" ADD CONSTRAINT "FK_e9d3d49c9779b47390961eb1cff" FOREIGN KEY ("featureFlagId") REFERENCES "feature_flag"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_segment_inclusion" ADD CONSTRAINT "FK_95161b8f3f8284268fd3af07f17" FOREIGN KEY ("segmentId") REFERENCES "segment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_segment_inclusion" ADD CONSTRAINT "FK_f9e3c925808cc88fe34cafa0ec3" FOREIGN KEY ("experimentId") REFERENCES "experiment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment" ADD CONSTRAINT "FK_335189d91114f3a71ff18be6243" FOREIGN KEY ("stratificationFactorStratificationFactorName") REFERENCES "stratification_factor"("stratificationFactorName") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "archived_stats" ADD CONSTRAINT "FK_df18fe5ea7298a1dc7bfb33b06f" FOREIGN KEY ("queryId") REFERENCES "query"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "query" ADD CONSTRAINT "FK_16b236f2ca1472930abdbaf048a" FOREIGN KEY ("metricKey") REFERENCES "metric"("key") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "query" ADD CONSTRAINT "FK_80e30ce407c8e0555a6ad46d659" FOREIGN KEY ("experimentId") REFERENCES "experiment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "log" ADD CONSTRAINT "FK_cea2ed3a494729d4b21edbd2983" FOREIGN KEY ("userId") REFERENCES "experiment_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_user" ADD CONSTRAINT "FK_f1d4193d241e06d2de07527c980" FOREIGN KEY ("originalUserId") REFERENCES "experiment_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_stratification_factor" ADD CONSTRAINT "FK_a314482a152dd63f49898feb468" FOREIGN KEY ("userId") REFERENCES "experiment_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_stratification_factor" ADD CONSTRAINT "FK_287fb490668d66047a1f8d96c1e" FOREIGN KEY ("factorName") REFERENCES "stratification_factor"("stratificationFactorName") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "experiment_audit_log" ADD CONSTRAINT "FK_89d077ecfd3b7cc18fe6d6a89f8" FOREIGN KEY ("userEmail") REFERENCES "user"("email") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduled_job" ADD CONSTRAINT "FK_8b449f6d80b8378f792c1a6bee2" FOREIGN KEY ("experimentId") REFERENCES "experiment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "explicit_individual_assignment" ADD CONSTRAINT "FK_6763c88d585ff2ca4ef849491e0" FOREIGN KEY ("previewUserId") REFERENCES "preview_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "explicit_individual_assignment" ADD CONSTRAINT "FK_502b25664bcdd4b6721122faf09" FOREIGN KEY ("experimentId") REFERENCES "experiment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "explicit_individual_assignment" ADD CONSTRAINT "FK_69752e8939b65a718aa4b556e76" FOREIGN KEY ("experimentConditionId") REFERENCES "experiment_condition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "monitored_decision_point" ADD CONSTRAINT "FK_be1ade8096668d342a8d37e8129" FOREIGN KEY ("userId") REFERENCES "experiment_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "monitored_decision_point_log" ADD CONSTRAINT "FK_4e9bf07b07327c60523614ceed0" FOREIGN KEY ("monitoredDecisionPointId") REFERENCES "monitored_decision_point"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "individual_exclusion" ADD CONSTRAINT "FK_43238be19de9500c290393b9078" FOREIGN KEY ("experimentId") REFERENCES "experiment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "individual_exclusion" ADD CONSTRAINT "FK_de26ba8251f4ebf8b9c8ccf6236" FOREIGN KEY ("userId") REFERENCES "experiment_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "individual_enrollment" ADD CONSTRAINT "FK_6bc8c85db258f328c7af93346e9" FOREIGN KEY ("experimentId") REFERENCES "experiment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "individual_enrollment" ADD CONSTRAINT "FK_c6b061b4c2e9cf33b19aea73e73" FOREIGN KEY ("partitionId") REFERENCES "decision_point"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "individual_enrollment" ADD CONSTRAINT "FK_b4575e2a0c125578c9744492c7c" FOREIGN KEY ("userId") REFERENCES "experiment_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "individual_enrollment" ADD CONSTRAINT "FK_4f4d2f2ec491226d4692ed400fc" FOREIGN KEY ("conditionId") REFERENCES "experiment_condition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_exclusion" ADD CONSTRAINT "FK_15ae48e288f94c0aab841cd8073" FOREIGN KEY ("experimentId") REFERENCES "experiment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_enrollment" ADD CONSTRAINT "FK_ae99aafabd65ee3251d59e1f5b0" FOREIGN KEY ("experimentId") REFERENCES "experiment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_enrollment" ADD CONSTRAINT "FK_151c40ca733232929477532903a" FOREIGN KEY ("partitionId") REFERENCES "decision_point"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_enrollment" ADD CONSTRAINT "FK_7479d73940ffee4afce253b3061" FOREIGN KEY ("conditionId") REFERENCES "experiment_condition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "segment_for_segment" ADD CONSTRAINT "FK_7cbe54e77df890c36415493e981" FOREIGN KEY ("childSegmentId") REFERENCES "segment"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "segment_for_segment" ADD CONSTRAINT "FK_cb101a942537f1fc0a7ef7994c4" FOREIGN KEY ("parentSegmentId") REFERENCES "segment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "metric_log" ADD CONSTRAINT "FK_81c6609c523e34b8f001cad7170" FOREIGN KEY ("metricKey") REFERENCES "metric"("key") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "metric_log" ADD CONSTRAINT "FK_c022cd84fd9fa789cbaee40b41c" FOREIGN KEY ("logId") REFERENCES "log"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "metric_log" DROP CONSTRAINT "FK_c022cd84fd9fa789cbaee40b41c"`);
        await queryRunner.query(`ALTER TABLE "metric_log" DROP CONSTRAINT "FK_81c6609c523e34b8f001cad7170"`);
        await queryRunner.query(`ALTER TABLE "segment_for_segment" DROP CONSTRAINT "FK_cb101a942537f1fc0a7ef7994c4"`);
        await queryRunner.query(`ALTER TABLE "segment_for_segment" DROP CONSTRAINT "FK_7cbe54e77df890c36415493e981"`);
        await queryRunner.query(`ALTER TABLE "group_enrollment" DROP CONSTRAINT "FK_7479d73940ffee4afce253b3061"`);
        await queryRunner.query(`ALTER TABLE "group_enrollment" DROP CONSTRAINT "FK_151c40ca733232929477532903a"`);
        await queryRunner.query(`ALTER TABLE "group_enrollment" DROP CONSTRAINT "FK_ae99aafabd65ee3251d59e1f5b0"`);
        await queryRunner.query(`ALTER TABLE "group_exclusion" DROP CONSTRAINT "FK_15ae48e288f94c0aab841cd8073"`);
        await queryRunner.query(`ALTER TABLE "individual_enrollment" DROP CONSTRAINT "FK_4f4d2f2ec491226d4692ed400fc"`);
        await queryRunner.query(`ALTER TABLE "individual_enrollment" DROP CONSTRAINT "FK_b4575e2a0c125578c9744492c7c"`);
        await queryRunner.query(`ALTER TABLE "individual_enrollment" DROP CONSTRAINT "FK_c6b061b4c2e9cf33b19aea73e73"`);
        await queryRunner.query(`ALTER TABLE "individual_enrollment" DROP CONSTRAINT "FK_6bc8c85db258f328c7af93346e9"`);
        await queryRunner.query(`ALTER TABLE "individual_exclusion" DROP CONSTRAINT "FK_de26ba8251f4ebf8b9c8ccf6236"`);
        await queryRunner.query(`ALTER TABLE "individual_exclusion" DROP CONSTRAINT "FK_43238be19de9500c290393b9078"`);
        await queryRunner.query(`ALTER TABLE "monitored_decision_point_log" DROP CONSTRAINT "FK_4e9bf07b07327c60523614ceed0"`);
        await queryRunner.query(`ALTER TABLE "monitored_decision_point" DROP CONSTRAINT "FK_be1ade8096668d342a8d37e8129"`);
        await queryRunner.query(`ALTER TABLE "explicit_individual_assignment" DROP CONSTRAINT "FK_69752e8939b65a718aa4b556e76"`);
        await queryRunner.query(`ALTER TABLE "explicit_individual_assignment" DROP CONSTRAINT "FK_502b25664bcdd4b6721122faf09"`);
        await queryRunner.query(`ALTER TABLE "explicit_individual_assignment" DROP CONSTRAINT "FK_6763c88d585ff2ca4ef849491e0"`);
        await queryRunner.query(`ALTER TABLE "scheduled_job" DROP CONSTRAINT "FK_8b449f6d80b8378f792c1a6bee2"`);
        await queryRunner.query(`ALTER TABLE "experiment_audit_log" DROP CONSTRAINT "FK_89d077ecfd3b7cc18fe6d6a89f8"`);
        await queryRunner.query(`ALTER TABLE "user_stratification_factor" DROP CONSTRAINT "FK_287fb490668d66047a1f8d96c1e"`);
        await queryRunner.query(`ALTER TABLE "user_stratification_factor" DROP CONSTRAINT "FK_a314482a152dd63f49898feb468"`);
        await queryRunner.query(`ALTER TABLE "experiment_user" DROP CONSTRAINT "FK_f1d4193d241e06d2de07527c980"`);
        await queryRunner.query(`ALTER TABLE "log" DROP CONSTRAINT "FK_cea2ed3a494729d4b21edbd2983"`);
        await queryRunner.query(`ALTER TABLE "query" DROP CONSTRAINT "FK_80e30ce407c8e0555a6ad46d659"`);
        await queryRunner.query(`ALTER TABLE "query" DROP CONSTRAINT "FK_16b236f2ca1472930abdbaf048a"`);
        await queryRunner.query(`ALTER TABLE "archived_stats" DROP CONSTRAINT "FK_df18fe5ea7298a1dc7bfb33b06f"`);
        await queryRunner.query(`ALTER TABLE "experiment" DROP CONSTRAINT "FK_335189d91114f3a71ff18be6243"`);
        await queryRunner.query(`ALTER TABLE "experiment_segment_inclusion" DROP CONSTRAINT "FK_f9e3c925808cc88fe34cafa0ec3"`);
        await queryRunner.query(`ALTER TABLE "experiment_segment_inclusion" DROP CONSTRAINT "FK_95161b8f3f8284268fd3af07f17"`);
        await queryRunner.query(`ALTER TABLE "feature_flag_segment_inclusion" DROP CONSTRAINT "FK_e9d3d49c9779b47390961eb1cff"`);
        await queryRunner.query(`ALTER TABLE "feature_flag_segment_inclusion" DROP CONSTRAINT "FK_e0abd5d8d0200b9e4d2fecf139e"`);
        await queryRunner.query(`ALTER TABLE "feature_flag_exposure" DROP CONSTRAINT "FK_6cefc76de0ca7c9a38faae5a8c4"`);
        await queryRunner.query(`ALTER TABLE "feature_flag_exposure" DROP CONSTRAINT "FK_6908f3ead6dd3a6fd4ce38514e6"`);
        await queryRunner.query(`ALTER TABLE "feature_flag_segment_exclusion" DROP CONSTRAINT "FK_d45d8b0089b0965c79b57fe84e7"`);
        await queryRunner.query(`ALTER TABLE "feature_flag_segment_exclusion" DROP CONSTRAINT "FK_b592d039e8ae2eed7a00c89cab0"`);
        await queryRunner.query(`ALTER TABLE "individual_for_segment" DROP CONSTRAINT "FK_cb84433b17891682f9a77126754"`);
        await queryRunner.query(`ALTER TABLE "group_for_segment" DROP CONSTRAINT "FK_715bbd2f483a715789a991123eb"`);
        await queryRunner.query(`ALTER TABLE "experiment_segment_exclusion" DROP CONSTRAINT "FK_7d22a811ae04d2ed1b8af0e9c05"`);
        await queryRunner.query(`ALTER TABLE "experiment_segment_exclusion" DROP CONSTRAINT "FK_915022e01487b0245a16cbc55f3"`);
        await queryRunner.query(`ALTER TABLE "state_time_log" DROP CONSTRAINT "FK_aa0df63ad4adcf2e827eaad3338"`);
        await queryRunner.query(`ALTER TABLE "experiment_condition" DROP CONSTRAINT "FK_390a67a227a832e28d48d33607e"`);
        await queryRunner.query(`ALTER TABLE "level_combination_element" DROP CONSTRAINT "FK_ecec1a2e76e475ee9f4c14ad94e"`);
        await queryRunner.query(`ALTER TABLE "level_combination_element" DROP CONSTRAINT "FK_6884570d63bde354d65406ceb3f"`);
        await queryRunner.query(`ALTER TABLE "level" DROP CONSTRAINT "FK_0d95bcd7511d345903a8c6b8481"`);
        await queryRunner.query(`ALTER TABLE "factor" DROP CONSTRAINT "FK_2dba7d958204335092fdfb5b337"`);
        await queryRunner.query(`ALTER TABLE "condition_payload" DROP CONSTRAINT "FK_017f4e5a324cb198939fff2af8c"`);
        await queryRunner.query(`ALTER TABLE "condition_payload" DROP CONSTRAINT "FK_1b19d3c212f0314144de579a120"`);
        await queryRunner.query(`ALTER TABLE "decision_point" DROP CONSTRAINT "FK_a12b2ac5e10ea27d692b43fd80c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c022cd84fd9fa789cbaee40b41"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81c6609c523e34b8f001cad717"`);
        await queryRunner.query(`DROP TABLE "metric_log"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb101a942537f1fc0a7ef7994c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cbe54e77df890c36415493e98"`);
        await queryRunner.query(`DROP TABLE "segment_for_segment"`);
        await queryRunner.query(`DROP TABLE "experiment_error"`);
        await queryRunner.query(`DROP TYPE "public"."experiment_error_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_151c40ca733232929477532903"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae99aafabd65ee3251d59e1f5b"`);
        await queryRunner.query(`DROP TABLE "group_enrollment"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15ae48e288f94c0aab841cd807"`);
        await queryRunner.query(`DROP TABLE "group_exclusion"`);
        await queryRunner.query(`DROP TYPE "public"."group_exclusion_exclusioncode_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f4d2f2ec491226d4692ed400f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4575e2a0c125578c9744492c7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c6b061b4c2e9cf33b19aea73e7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bc8c85db258f328c7af93346e"`);
        await queryRunner.query(`DROP TABLE "individual_enrollment"`);
        await queryRunner.query(`DROP TYPE "public"."individual_enrollment_enrollmentcode_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de26ba8251f4ebf8b9c8ccf623"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43238be19de9500c290393b907"`);
        await queryRunner.query(`DROP TABLE "individual_exclusion"`);
        await queryRunner.query(`DROP TYPE "public"."individual_exclusion_exclusioncode_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e9bf07b07327c60523614ceed"`);
        await queryRunner.query(`DROP TABLE "monitored_decision_point_log"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be1ade8096668d342a8d37e812"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ac3dba0b5e060528dbdc34b51"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_400734a43360ef813c6080ddbb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c8f3c5d7e18ba5b504b91d96c2"`);
        await queryRunner.query(`DROP TABLE "monitored_decision_point"`);
        await queryRunner.query(`DROP TABLE "mooclet_policy_support"`);
        await queryRunner.query(`DROP TYPE "public"."mooclet_policy_support_policy_name_enum"`);
        await queryRunner.query(`DROP TABLE "preview_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_502b25664bcdd4b6721122faf0"`);
        await queryRunner.query(`DROP TABLE "explicit_individual_assignment"`);
        await queryRunner.query(`DROP TABLE "scheduled_job"`);
        await queryRunner.query(`DROP TABLE "setting"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`DROP TABLE "experiment_audit_log"`);
        await queryRunner.query(`DROP TYPE "public"."experiment_audit_log_type_enum"`);
        await queryRunner.query(`DROP TABLE "user_stratification_factor"`);
        await queryRunner.query(`DROP TABLE "experiment_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cea2ed3a494729d4b21edbd298"`);
        await queryRunner.query(`DROP TABLE "log"`);
        await queryRunner.query(`DROP TABLE "metric"`);
        await queryRunner.query(`DROP TYPE "public"."metric_type_enum"`);
        await queryRunner.query(`DROP TABLE "query"`);
        await queryRunner.query(`DROP TYPE "public"."query_repeatedmeasure_enum"`);
        await queryRunner.query(`DROP TABLE "archived_stats"`);
        await queryRunner.query(`DROP TABLE "experiment"`);
        await queryRunner.query(`DROP TYPE "public"."experiment_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."experiment_filtermode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."experiment_assignmentalgorithm_enum"`);
        await queryRunner.query(`DROP TYPE "public"."experiment_conditionorder_enum"`);
        await queryRunner.query(`DROP TYPE "public"."experiment_postexperimentrule_enum"`);
        await queryRunner.query(`DROP TYPE "public"."experiment_assignmentunit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."experiment_consistencyrule_enum"`);
        await queryRunner.query(`DROP TYPE "public"."experiment_state_enum"`);
        await queryRunner.query(`DROP TABLE "stratification_factor"`);
        await queryRunner.query(`DROP TABLE "experiment_segment_inclusion"`);
        await queryRunner.query(`DROP TABLE "segment"`);
        await queryRunner.query(`DROP TYPE "public"."segment_type_enum"`);
        await queryRunner.query(`DROP TABLE "feature_flag_segment_inclusion"`);
        await queryRunner.query(`DROP TABLE "feature_flag"`);
        await queryRunner.query(`DROP TYPE "public"."feature_flag_filtermode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."feature_flag_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cefc76de0ca7c9a38faae5a8c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6908f3ead6dd3a6fd4ce38514e"`);
        await queryRunner.query(`DROP TABLE "feature_flag_exposure"`);
        await queryRunner.query(`DROP TABLE "feature_flag_segment_exclusion"`);
        await queryRunner.query(`DROP TABLE "individual_for_segment"`);
        await queryRunner.query(`DROP TABLE "group_for_segment"`);
        await queryRunner.query(`DROP TABLE "experiment_segment_exclusion"`);
        await queryRunner.query(`DROP TABLE "state_time_log"`);
        await queryRunner.query(`DROP TYPE "public"."state_time_log_tostate_enum"`);
        await queryRunner.query(`DROP TYPE "public"."state_time_log_fromstate_enum"`);
        await queryRunner.query(`DROP TABLE "experiment_condition"`);
        await queryRunner.query(`DROP TABLE "level_combination_element"`);
        await queryRunner.query(`DROP TABLE "level"`);
        await queryRunner.query(`DROP TYPE "public"."level_payloadtype_enum"`);
        await queryRunner.query(`DROP TABLE "factor"`);
        await queryRunner.query(`DROP TABLE "condition_payload"`);
        await queryRunner.query(`DROP TYPE "public"."condition_payload_payloadtype_enum"`);
        await queryRunner.query(`DROP TABLE "decision_point"`);
    }

}
