import { randomUUID } from 'crypto';
import Container from 'typedi';
import { DataSource, In } from 'typeorm';
import { SEGMENT_TYPE, STANDARD_LIST_TYPE, SYSTEM_USER_EMAIL } from 'upgrade_types';
import { FeatureFlag } from '../../../src/api/models/FeatureFlag';
import { FeatureFlagSegmentExclusion } from '../../../src/api/models/FeatureFlagSegmentExclusion';
import { FeatureFlagSegmentInclusion } from '../../../src/api/models/FeatureFlagSegmentInclusion';
import { GroupForSegment } from '../../../src/api/models/GroupForSegment';
import { IndividualForSegment } from '../../../src/api/models/IndividualForSegment';
import { Segment } from '../../../src/api/models/Segment';
import { User } from '../../../src/api/models/User';
import { FeatureFlagService } from '../../../src/api/services/FeatureFlagService';
import { SegmentService } from '../../../src/api/services/SegmentService';
import { UpgradeLogger } from '../../../src/lib/logger/UpgradeLogger';

const createSegment = async (connection: DataSource, type: SEGMENT_TYPE, subSegments: Segment[] = []) => {
  const id = randomUUID();
  const segment = await connection.getRepository(Segment).save({
    id,
    name: `cleanup-${id}`,
    context: 'cleanup-test',
    type,
    listType: subSegments.length ? STANDARD_LIST_TYPE.SEGMENT : STANDARD_LIST_TYPE.INDIVIDUAL,
    subSegments,
  });
  await connection.getRepository(IndividualForSegment).insert({ segmentId: id, userId: 'cleanup-user' });
  await connection.getRepository(GroupForSegment).insert({ segmentId: id, groupId: 'cleanup-group', type: 'class' });
  return segment;
};

const expectRemainingSegments = async (connection: DataSource, fixtureIds: string[], remainingIds: string[]) => {
  const segments = await connection.getRepository(Segment).findBy({ id: In(fixtureIds) });
  const individuals = await connection.getRepository(IndividualForSegment).findBy({ segmentId: In(fixtureIds) });
  const groups = await connection.getRepository(GroupForSegment).findBy({ segmentId: In(fixtureIds) });
  const expected = [...remainingIds].sort();
  expect(segments.map(({ id }) => id).sort()).toEqual(expected);
  expect(individuals.map(({ segmentId }) => segmentId).sort()).toEqual(expected);
  expect(groups.map(({ segmentId }) => segmentId).sort()).toEqual(expected);
};

// A real PostgreSQL error exercises transaction rollback, including writes completed before the error.
const withDeleteFailure = async (connection: DataSource, segmentId: string, work: () => Promise<void>) => {
  try {
    // Replace test objects left behind by an interrupted run.
    await connection.query(`
      CREATE OR REPLACE FUNCTION cleanup_test_reject_delete() RETURNS trigger AS $$
      BEGIN
        IF OLD.id = TG_ARGV[0]::uuid THEN
          RAISE EXCEPTION 'forced cleanup failure';
        END IF;
        RETURN OLD;
      END;
      $$ LANGUAGE plpgsql
    `);
    await connection.query('DROP TRIGGER IF EXISTS cleanup_test_reject_delete ON segment');
    // segmentId is generated by randomUUID within this test fixture.
    await connection.query(`
      CREATE TRIGGER cleanup_test_reject_delete BEFORE DELETE ON segment
      FOR EACH ROW EXECUTE FUNCTION cleanup_test_reject_delete('${segmentId}')
    `);
    await work();
  } finally {
    await connection.query('DROP TRIGGER IF EXISTS cleanup_test_reject_delete ON segment');
    await connection.query('DROP FUNCTION IF EXISTS cleanup_test_reject_delete()');
  }
};

export const FeatureFlagDeleteCleanup = async (connection: DataSource, failedList?: 'inclusion' | 'exclusion') => {
  const publicSegment = await createSegment(connection, SEGMENT_TYPE.PUBLIC);
  const included = await createSegment(connection, SEGMENT_TYPE.PRIVATE, [publicSegment]);
  const excluded = await createSegment(connection, SEGMENT_TYPE.PRIVATE);
  const flag = await connection.getRepository(FeatureFlag).save({
    id: randomUUID(),
    name: 'Cleanup test flag',
    key: randomUUID(),
    description: 'Deletion regression fixture',
    context: ['cleanup-test'],
  });
  await connection.getRepository(FeatureFlagSegmentInclusion).insert({
    featureFlagId: flag.id,
    segmentId: included.id,
    listType: STANDARD_LIST_TYPE.SEGMENT,
  });
  await connection.getRepository(FeatureFlagSegmentExclusion).insert({
    featureFlagId: flag.id,
    segmentId: excluded.id,
    listType: STANDARD_LIST_TYPE.INDIVIDUAL,
  });
  const user = await connection.getRepository(User).findOneByOrFail({ email: SYSTEM_USER_EMAIL });
  const service = Container.get(FeatureFlagService);
  const ids = [publicSegment.id, included.id, excluded.id];

  if (failedList) {
    await withDeleteFailure(connection, failedList === 'inclusion' ? included.id : excluded.id, async () => {
      await expect(service.delete(flag.id, user, new UpgradeLogger())).rejects.toThrow('forced cleanup failure');
    });
    expect(await connection.getRepository(FeatureFlag).countBy({ id: flag.id })).toBe(1);
    await expectRemainingSegments(connection, ids, ids);
    expect(await connection.getRepository(FeatureFlagSegmentInclusion).countBy({ featureFlagId: flag.id })).toBe(1);
    expect(await connection.getRepository(FeatureFlagSegmentExclusion).countBy({ featureFlagId: flag.id })).toBe(1);
    const restored = await connection.getRepository(Segment).findOneOrFail({
      where: { id: included.id },
      relations: { subSegments: true },
    });
    expect(restored.subSegments.map(({ id }) => id)).toEqual([publicSegment.id]);
  } else {
    // Success-path coverage; deferred cleanup in the unit tests verifies that deletion actually waits.
    const deleted = await service.delete(flag.id, user, new UpgradeLogger());
    // Preserve the existing repository response (an array despite the service's declared return type).
    expect(deleted).toEqual([expect.objectContaining({ id: flag.id })]);
    expect(await connection.getRepository(FeatureFlag).countBy({ id: flag.id })).toBe(0);
    await expectRemainingSegments(connection, ids, [publicSegment.id]);
    expect(await connection.getRepository(FeatureFlagSegmentInclusion).countBy({ featureFlagId: flag.id })).toBe(0);
    expect(await connection.getRepository(FeatureFlagSegmentExclusion).countBy({ featureFlagId: flag.id })).toBe(0);
  }
};

export const SegmentDeleteCleanup = async (connection: DataSource, failCleanup = false) => {
  const publicChild = await createSegment(connection, SEGMENT_TYPE.PUBLIC);
  const leaf = await createSegment(connection, SEGMENT_TYPE.PRIVATE);
  const owned = await createSegment(connection, SEGMENT_TYPE.PRIVATE, [leaf]);
  const root = await createSegment(connection, SEGMENT_TYPE.PUBLIC, [owned, publicChild]);
  const ids = [root.id, owned.id, leaf.id, publicChild.id];
  const service = Container.get(SegmentService);

  if (failCleanup) {
    // The leaf is deleted first; failing its private parent must restore the leaf and its members too.
    await withDeleteFailure(connection, owned.id, async () => {
      await expect(service.deleteSegment(root.id, new UpgradeLogger())).rejects.toThrow('forced cleanup failure');
    });
    await expectRemainingSegments(connection, ids, ids);
    const restored = await connection.getRepository(Segment).findOneOrFail({
      where: { id: root.id },
      relations: { subSegments: { subSegments: true } },
    });
    expect(restored.subSegments.map(({ id }) => id).sort()).toEqual([owned.id, publicChild.id].sort());
    expect(restored.subSegments.find(({ id }) => id === owned.id).subSegments.map(({ id }) => id)).toEqual([leaf.id]);
  } else {
    await expect(service.deleteSegment(root.id, new UpgradeLogger())).resolves.toMatchObject({ id: root.id });
    await expectRemainingSegments(connection, ids, [publicChild.id]);
    const retained = await connection.getRepository(Segment).findOneOrFail({
      where: { id: publicChild.id },
      relations: { segments: true },
    });
    expect(retained.segments).toEqual([]);
  }
};
