#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


# Testing Frontend
cd frontend
npm run lint:fix
npm test
cd ..

# Testing Backend Upgrade
cd backend/packages/Upgrade
npm start lint && npm start typecheck && npm test
