#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Testing JS Client Lib
cd clientlib/js
lint-staged
cd ../../

# Testing Frontend
cd frontend
npm test
cd ..

# Testing Backend Upgrade
cd backend/packages/Upgrade
npm start lint && npm start typecheck && npm test
