modules = {
    "alg1_module1": ["identifying_quantities", "introduction_to_function_families", "functions_relations_evaluation", "identifying_parts_of_complex_algebraic_expressions", "sequences_1", "sequences_2", "sequences_3", "exploring_linear_regression", "using_linear_regression", "interpreting_lines_of_best_fit", "analyzing_residuals_of_lines_of_best_fit"],
    "alg1_module2": ["sequences_4_linear_functions", "understanding_linear_functions", "exploring_graphs_of_linear_functions", "graphs_of_functions-1", "multiple_representations_of_linear_functions", "worksheet_grapher_a1_lin_mod_mult_rep", "compare_functions_diff_reps_linear", "solve_literal_equation_side_by_side", "solve_literal_equation_solo", "linear_inequalities_numberline", "linear_inequalities_solver_both_sides", "representing_compound_inequalities", "representing_systems_of_linear_functions", "linear_system_solving_2", "linear_system_solving_3", "exploring_linear_inequalities", "graph_setup_linear_inequalities-1", "graph_setup_linear_systems-1", "building_absolute_value_functions", "absolute_value_plot_equality", "absolute_value_solve_equality", "reasoning_about_absolute_value_inequalities", "introduction_to_piecewise_functions", "piecewise_functions_linear_graph", "interpreting_piecewise_functions", "piecewise_functions_linear_use", "analyzing_step_functions"],
    "alg1_module3": ["sequences_4_exponential_functions", "introduction_to_exponential_functions", "relating_the_domain_to_exponential_functions", "using_the_properties_of_exponents", "properties_of_rational_exponents", "rewriting_expressions_with_radical_and_rational_exponents", "common_base_exponentials_contextual", "introduction_to_transforming_exponential_functions", "function_transforms_linear_exponential_vertical", "function_transforms_linear_exponential_horizontal", "function_transforms_linear_exponential_reflectdilate", "function_transforms_linear_exponential_table", "function_transforms_linear_exponential_multiple", "recognizing_linear_and_exponential_models", "recognizing_growth_and_decay", "calculating_and_interpreting_average_rate_of_change", "quadratic_models_exponential_basic", "quadratic_models_exponential_extended", "compare_functions_diff_reps_exponential", "exponential_equations_solving_graphically"],
    "alg1_module4": ["measures_central_tendency-2", "measures_central_tendency-3", "comparing_and_interpreting_center_and_spread", "standard_deviation", "categorical_tables_frequency_tabulation", "categorical_tables_frequency_analysis", "categorical_tables_relative_frequency_tabulation", "categorical_tables_relative_frequency_analysis", "categorical_tables_conditional_frequency_tabulation", "categorical_tables_conditional_frequency_analysis"],
    "alg1_module5": ["quadratic_models_factored_monomial_binomial", "quadratic_models_factored_two_binomials", "maximizing_area", "quadratic_models_projectile_motion", "recognizing_key_features_of_projectile_motion_graphs", "function_transforms_linear_quadratic_vertical", "function_transforms_linear_quadratic_horizontal", "function_transforms_linear_quadratic_reflectdilate", "function_transforms_linear_quadratic_table", "function_transforms_linear_quadratic_multiple", "identifying_properties_of_quadratic_functions", "sketching_polynomial_graphs_quads", "compare_functions_diff_reps_quadratic", "introduction_to_polynomial_arithmetic", "operating_with_functions_on_the_coordinate_plane", "solver_add_subtract_poly_add_quad", "solver_add_subtract_poly_subtract", "polynomial_multiplication_binomial_scaffolded", "polynomial_multiplication_binomial_unscaffolded", "making_sense_of_roots_and_zeros", "simplify_quadratic-1", "solve_quadratic_equation_1", "simplify_quadratic-2", "simplify_quadratic-3", "simplify_quadratic-4", "solve_quadratic_equation_factoring_1", "problem_solving_by_factoring", "completing_the_square", "problem_solving_by_completing_the_square", "deriving_the_quadratic_formula", "converting_quadratics_to_general_form", "converting_quadratics_to_factored_form", "converting_quadratics_to_vertex_form", "quadratic_models_general_regression", "functions_relations_addsubtract", "functions_relations_recognize_inverses"],
    "alg2_module1": ["exploring_and_analyzing_patterns", "comparing_familiar_function_representations", "graphs_of_functions-1", "transforming_functions", "examining_the_shape_and_structure_of_functions", "quadratic_models_factored_review", "solve_quadratic_equation_review", "function_transforms_quadratic_review", "introduction_to_complex_numbers", "simplify_complex_numbers_radicals", "simplifying_powers_of_i", "simplify_complex_numbers_addsub", "simplify_complex_numbers_mult", "quadratics_with_complex_roots", "modeling_polynomial_functions", "analyzing_polynomial_functions", "classify_polynomials", "interpreting_key_features_of_graphs_in_terms_of_quantities", "key_characteristics_polynomials", "identifying_zeros_of_polynomials", "sketching_polynomial_graphs_polys", "understanding_average_rate_of_change_of_polynomial_functions", "compare_functions_diff_reps_polynomial"],
    "alg2_module2": ["polynomial_multiplication_poly_scaffolded", "polynomial_multiplication_poly_unscaffolded", "solve_quadratic_equation_factoring_1", "synthetic_division", "factoring_higher_order_polynomials", "solving_polynomial_functions", "pascal_s_triangle", "binomial_theorem", "exploring_polynomial_regression", "solving_polynomial_inequalities", "introduction_to_rational_functions", "rational_models_2", "solver_simplify_rational_factor_cancel", "solver_simplify_rational_add_subt", "solver_simplify_rational_mult_div", "rational_equations_1", "rational_models_1", "rational_models_3", "work_mixture_distance-1", "work_mixture_distance-2"],
    "alg2_module3": ["investigating_inverses_of_functions", "graphs_of_inverses", "graphing_square_root_functions", "functions_relations_calculate_inverses", "simplify_radical_1", "simplify_radical_2_add", "simplify_radical_3_mult", "simplify_radical_4_div", "simplify_radical_5_var", "simplify_radical_add_subtract_variables", "properties_of_exponential_graphs", "introduction_to_logarithmic_functions", "solving_base_two_ten_equations", "solving_base_e_equations", "solving_any_base_equations", "introduction_to_finite_geometric_series", "finite_geometric_series"],
    "alg2_module4": ["understanding_the_unit_circle", "choosing_trig_functions", "proving_the_pythagorean_identity", "using_the_pythagorean_identity", "solver_one_step_trig_equations_sin_cos_notype", "solver_one_step_trig_equations_tan_notype", "solver_one_step_trig_equations_mix_notype"],
    "alg2_module5": ["data_displays_constructing_relative_frequency_histograms", "normal_distribution_whole_zscore_percentiles", "normal_distribution_zscore_percentiles", "normal_distribution_probability"],
    "geo_module1": ["lines_rays_segments_angles_naming", "lines_rays_segments_angles_measuring", "introduction_to_parallel_and_perpendicular_lines", "equation_line_parallel_perpendicular", "deriving_the_distance_formula", "distance_midpoint_distance_formula_", "distance_midpoint_area_perimeter_", "introduction_to_circles", "determining_central_and_inscribed_angles_in_circles", "angles_of_an_inscribed_quadrilateral", "developing_definitions_of_rigid_motions", "exploring_rigid_motions_and_dilations", "geo_transforms_sequences", "rotations_and_reflections_on_the_plane", "reflectional_rotational_symmetry_reflectional", "reflectional_rotational_symmetry_rotational"],
    "geo_module2": ["introduction_to_triangle_congruence", "using_triangle_congruence", "angle_properties_justifying", "angle_properties_calculating", "introduction_to_proofs", "proof_connecting_steps", "proof_completing_measures", "using_angle_theorems", "classifying_angles_formed_by_a_transversal", "lines_cut_by_transversal_single", "lines_cut_by_transversal_multiple", "proofs_parallel_lines_theorems", "proofs_parallel_lines_converse_theorems", "proofs_congruent_triangles_sas_sss", "proofs_congruent_triangles_aas_asa", "proof_using_congruent_tri", "proof_triangle_theorems_proving", "proof_triangle_theorems_using", "understanding_parallelograms", "properties_of_parallelograms", "proof_parallelogram_theorems", "introduction_to_special_right_triangles", "pythag_diagram_special", "determining_interior_and_exterior_angles_in_circles", "proofs_congruent_triangles_hl_ha"],
    "geo_module3": ["understanding_similarity", "similar_triangles", "proof_similar_triangles", "partitioning_segments_in_given_ratios", "distance_midpoint_intermediate_points_", "introduction_to_trigonometric_ratios", "relating_sines_and_cosines_of_complementary_angles", "right_triangle_trig_single", "right_triangle_trig_double"],
    "geo_module4": ["relating_arc_length_and_radius", "determining_chords_in_circles_in_circles", "calculating_the_area_of_a_sector", "creating_three_dimensional_shapes_from_two_dimensional_figures", "volume_surface_area_cylinder_vol", "volume_surface_area_sq_pyramid_vol", "volume_surface_area_cone_vol", "volume_surface_area_sphere_vol", "visualizing_cross_sections_of_three_dimensional_shapes", "deriving_the_equation_of_a_circle", "determining_the_radius_and_center_of_a_circle"],
    "geo_module5": ["independent_events", "conditional_probability", "understanding_frequency_tables", "recognizing_concepts_of_conditional_probability", "compound_probability"],
    "im1_module2": ["sequences_4_linear_functions", "understanding_linear_functions", "exploring_graphs_of_linear_functions", "graphs_of_functions-1", "multiple_representations_of_linear_functions", "worksheet_grapher_a1_lin_mod_mult_rep", "compare_functions_diff_reps_linear", "introduction_to_parallel_and_perpendicular_lines", "equation_line_parallel_perpendicular", "solve_literal_equation_side_by_side", "solve_literal_equation_solo", "linear_inequalities_numberline", "linear_inequalities_solver_both_sides", "representing_compound_inequalities", "representing_systems_of_linear_functions", "linear_system_solving_2", "linear_system_solving_3", "exploring_linear_inequalities", "graph_setup_linear_inequalities-1", "graph_setup_linear_systems-1", "deriving_the_distance_formula", "distance_midpoint_distance_formula_", "distance_midpoint_area_perimeter_"],
    "im1_module5": ["lines_rays_segments_angles_naming", "lines_rays_segments_angles_measuring", "developing_definitions_of_rigid_motions", "exploring_rigid_motions_and_dilations", "geo_transforms_sequences", "rotations_and_reflections_on_the_plane", "reflectional_rotational_symmetry_reflectional", "reflectional_rotational_symmetry_rotational", "introduction_to_triangle_congruence", "using_triangle_congruence"],
    "im2_module1": ["lines_rays_segments_angles_naming", "lines_rays_segments_angles_measuring", "introduction_to_circles", "determining_central_and_inscribed_angles_in_circles", "angles_of_an_inscribed_quadrilateral", "proofs_congruent_triangles_hl_ha", "understanding_parallelograms", "properties_of_parallelograms", "proof_parallelogram_theorems", "angle_properties_justifying", "angle_properties_calculating", "introduction_to_proofs", "proof_connecting_steps", "proof_completing_measures", "using_angle_theorems", "classifying_angles_formed_by_a_transversal", "lines_cut_by_transversal_single", "lines_cut_by_transversal_multiple", "proofs_parallel_lines_theorems", "proofs_parallel_lines_converse_theorems", "proofs_congruent_triangles_sas_sss", "proofs_congruent_triangles_aas_asa", "proof_using_congruent_tri", "proof_triangle_theorems_proving", "proof_triangle_theorems_using", "introduction_to_special_right_triangles", "pythag_diagram_special", "determining_interior_and_exterior_angles_in_circles"],
    "im2_module2": ["understanding_similarity", "similar_triangles", "proof_similar_triangles", "partitioning_segments_in_given_ratios", "distance_midpoint_intermediate_points_", "introduction_to_trigonometric_ratios", "relating_sines_and_cosines_of_complementary_angles", "right_triangle_trig_single", "right_triangle_trig_double", "relating_arc_length_and_radius", "determining_chords_in_circles_in_circles", "calculating_the_area_of_a_sector", "creating_three_dimensional_shapes_from_two_dimensional_figures", "volume_surface_area_cylinder_vol", "volume_surface_area_sq_pyramid_vol", "volume_surface_area_cone_vol", "volume_surface_area_sphere_vol"],
    "im2_module3": ["building_absolute_value_functions", "absolute_value_plot_equality", "absolute_value_solve_equality", "reasoning_about_absolute_value_inequalities", "introduction_to_piecewise_functions", "piecewise_functions_linear_graph", "interpreting_piecewise_functions", "piecewise_functions_linear_use", "analyzing_step_functions", "recognizing_linear_and_exponential_models", "recognizing_growth_and_decay", "calculating_and_interpreting_average_rate_of_change", "quadratic_models_exponential_basic", "quadratic_models_exponential_extended", "compare_functions_diff_reps_exponential", "using_the_properties_of_exponents", "properties_of_rational_exponents", "rewriting_expressions_with_radical_and_rational_exponents", "common_base_exponentials_contextual", "introduction_to_transforming_exponential_functions", "function_transforms_linear_exponential_vertical", "function_transforms_linear_exponential_horizontal", "function_transforms_linear_exponential_reflectdilate", "function_transforms_linear_exponential_table", "function_transforms_linear_exponential_multiple", "quadratic_models_factored_monomial_binomial", "quadratic_models_factored_two_binomials", "maximizing_area", "quadratic_models_projectile_motion", "recognizing_key_features_of_projectile_motion_graphs", "function_transforms_linear_quadratic_vertical", "function_transforms_linear_quadratic_horizontal", "function_transforms_linear_quadratic_reflectdilate", "function_transforms_linear_quadratic_table", "function_transforms_linear_quadratic_multiple", "identifying_properties_of_quadratic_functions", "sketching_polynomial_graphs_quads", "compare_functions_diff_reps_quadratic"],
    "im2_module4": ["introduction_to_polynomial_arithmetic", "operating_with_functions_on_the_coordinate_plane", "solver_add_subtract_poly_add_quad", "solver_add_subtract_poly_subtract", "polynomial_multiplication_binomial_scaffolded", "polynomial_multiplication_binomial_unscaffolded", "making_sense_of_roots_and_zeros", "simplify_quadratic-1", "solve_quadratic_equation_1", "simplify_quadratic-2", "simplify_quadratic-3", "simplify_quadratic-4", "solve_quadratic_equation_factoring_1", "problem_solving_by_factoring", "completing_the_square", "problem_solving_by_completing_the_square", "deriving_the_quadratic_formula", "converting_quadratics_to_general_form", "converting_quadratics_to_factored_form", "converting_quadratics_to_vertex_form", "introduction_to_complex_numbers", "simplify_complex_numbers_radicals", "simplifying_powers_of_i", "simplify_complex_numbers_addsub", "simplify_complex_numbers_mult", "quadratics_with_complex_roots", "quadratic_models_general_regression", "functions_relations_addsubtract", "functions_relations_recognize_inverses", "deriving_the_equation_of_a_circle", "determining_the_radius_and_center_of_a_circle"],
    "course1_module1": ["commutative_and_associative_properties", "exploring_the_distributive_property_with_numeric_expressions", "using_the_distributive_property_with_numeric_expressions", "identifying_greatest_common_factors_and_least_common_multiples", "area_perimeter_mix_rectangular", "developing_area_formulas", "area_perimeter_mix_rectangle_derived", "solving_area_problems", "area_perimeter_composition", "representing_fraction_division", "fraction_division_model", "developing_the_fraction_division_algorithm", "solver_mixed_number_mult_div", "convert_frac_dec_equivalent", "adding_and_subtracting_decimals", "decimal_ops_sums_and_differences", "exploring_decimal_facts", "decimal_ops_patterns", "multiplying_decimals", "decimal_ops_products", "dividing_decimals", "decimal_ops_whole_number_and_decimal_quotients", "decimal_ops_problem_solving", "determining_volume_using_unit_fraction_cubes", "volume_surface_area_right_prism_vol", "determining_surface_area_using_nets", "volume_surface_area_right_prism_sa"],
    "course1_module2": ["understanding_ratio_relationships", "equivalent_ratios", "multiple_representations_of_ratios", "equivalent_ratios_rates_solving_table", "equivalent_ratios_rates_solving_double_numberline", "equivalent_ratios_rates_solving_graph", "percent_models", "fraction_decimal_percent_conversions", "determining_a_part", "determining_a_whole", "ratio_proportion_ratio2", "converting_within_a_system", "converting_between_systems"],
    "course1_module3": ["expression_evaluation_one_step_int", "expression_evaluation_two_step_int", "writing_and_evaluating_exponent_expressions", "order_of_operations", "simplifying_numeric_expressions", "simplify_order_of_ops_expression_numeric_contrast_addsub_multdiv_intro", "simplify_order_of_ops_expression_numeric_four_ops_complex_intro", "simplify_order_of_ops_expression_numeric_parens_expon_intro", "simplify_order_of_ops_expression_numeric_mix_type_intro", "identifying_parts_of_simple_algebraic_expressions", "expression_evaluation_frac-dec-2", "expression_evaluation_multiple_variables", "modeling_equivalent_algebraic_expressions", "exploring_the_distributive_property_with_algebraic_expressions", "simplify_order_of_ops_expression_variable_contrast_addsub_multdiv_intro", "simplify_order_of_ops_expression_variable_four_ops_complex_intro", "simplify_order_of_ops_expression_variable_parens_expon_intro", "simplify_order_of_ops_expression_variable_mix_type_intro", "picture_algebra_mix", "picture_algebra_multiply_total_given", "picture_algebra_addsub_total_given", "worksheet_grapher_a1_patterns_1step_expr_ops", "using_substitution_to_determine_solutions", "solving_one_step_equations_with_a_balance", "representing_one_step_equations", "solve_linear_equation_1step_add_subtract_notype", "solve_linear_equation_1step_mult_div_notype", "solve_linear_equation_1step", "linear_inequalities_numberline_noneg", "using_substitution_to_identify_solutions_to_inequalities", "modeling_scenarios_with_equations", "analyzing_models_1step", "worksheet_grapher_a1_patterns_1step_eqn_ops", "worksheet_grapher_a1_solving_1step_int", "worksheet_grapher_a1_solving_1step_dec"],
    "course1_module4": ["introducing_negative_numbers", "representing_integers_on_number_lines", "using_absolute_value", "linear_inequalities_numberline", "exploring_symmetry_on_the_coordinate_plane", "identifying_and_interpreting_ordered_pairs", "plotting_points", "drawing_polygons_on_the_coordinate_plane", "writing_an_expression_from_a_scenario_table_or_graph", "worksheet_grapher_a1_four_quadrant_graphing_1step"],
    "course1_module5": ["analyzing_distributions_with_shape_center_and_spread", "creating_and_interpreting_stem_plots", "creating_and_interpreting_dot_plots", "creating_and_interpreting_histograms", "measures_central_tendency-1", "measures_central_tendency-2_intro", "measures_central_tendency-3", "calculating_mean_absolute_deviation", "using_mean_absolute_deviation", "constructing_box_and_whisker_plots", "interpreting_box_and_whisker_plots", "choosing_appropriate_measures"],
    "course2_module1": ["investigating_circles", "area_perimeter_circle_forwards", "fractional_rates", "ratio_proportion_ratio2", "proportional_relationships", "determining_characteristics_of_direct_variation_graphs", "ratio_proportion_prop1", "rewriting_proportions_as_products", "ratio_proportion_prop2", "exploring_proportions_and_direct_variation", "direct_variation_equation", "direct_variation_convert", "worksheet_grapher_a1_direct_variation", "fractional_percent_models", "converting_with_fractional_percents", "using_proportions_to_solve_percent_problems", "solving_simple_percent_problems", "ratio_proportion_change3", "ratio_proportion_change4", "sales_tax_discounts_one_rate", "sales_tax_discounts_two_rates", "analyzing_different_forms_of_expressions", "critical_attributes_of_similar_figures", "using_scale_drawings", "scale_drawings_3"],
    "course2_module2": ["understanding_opposites", "adding_and_subtracting_integers", "integer_add_subtract_nl_mix", "developing_algorithms_for_adding_and_subtracting_integers", "multiplying_and_dividing_integers", "converting_rational_numbers_to_decimals", "simplify_order_of_ops_expression_numeric_contrast_addsub_multdiv", "simplify_order_of_ops_expression_numeric_parens_expon", "simplify_order_of_ops_expression_numeric_mix_type_simple", "simplify_order_of_ops_expression_numeric_mix_type_complex"],
    "course2_module3": ["factoring_expressions", "simplify_order_of_ops_expression_variable_contrast_addsub_multdiv", "simplify_order_of_ops_expression_variable_four_ops_complex", "simplify_order_of_ops_expression_variable_parens_expon", "simplify_order_of_ops_expression_variable_complex", "simplify_order_of_ops_expression_variable_mix_type", "picture_algebra_mix_variable", "identifying_signs_of_starting_values_and_rates", "analyzing_models_2step_integers", "worksheet_grapher_a1_patterns_2step_expr", "conceptual_equations_2step_1var", "solve_linear_equation_2step_mult_notype", "solve_linear_equation_2step_mult_typein", "solve_linear_equation_2step_div_notype", "solve_linear_equation_2step_div_typein", "solve_linear_equation_2step", "linear_inequalities_numberline", "linear_inequalities_solver_1step", "linear_inequalities_solver_2step", "determining_the_value_of_an_independent_variable", "linear_relations_1", "worksheet_grapher_a1_solving_2step_int", "worksheet_grapher_a1_solving_2step_dec_frac", "graphs_of_equations", "using_graphs_to_solve_equations"],
    "course2_module4": ["determining_probabilities", "simple_probabilities", "comparing_theoretical_and_experimental_probabilities", "simulating_simple_events", "introduction_to_compound_events", "calculating_compound_probabilities", "simulating_compound_events", "distinguishing_between_populations_and_samples", "comparing_characteristics_of_data_displays", "comparing_populations_using_data_displays"],
    "course2_module5": ["calculating_angles", "classify_and_determine_angles", "visualizing_cross_sections_of_three_dimensional_shapes", "understanding_volume_of_right_prisms", "volume_surface_area_right_prism_vol-_backward", "volume_surface_area_sq_pyramid_vol", "volume_surface_area_sq_pyramid_vol-_backward"],
    "course3_module1": ["verifying_properties_of_rigid_motions", "geo_transforms_tr", "geo_transforms_re", "geo_transforms_ro", "describing_rigid_motions_using_coordinates", "defining_similarity", "geo_transforms_di", "geo_transforms_mix_single", "geo_transforms_mix_multiple", "describing_transformations_using_coordinates", "introduction_to_triangle_sum_and_exterior_angle_theorems", "classifying_angles_formed_by_a_transversal", "calculating_angles_formed_by_a_transversal", "lines_cut_by_transversal_single"],
    "course3_module2": ["representing_proportional_relationships_algebraically", "worksheet_grapher_a1_direct_variation", "understanding_the_slopes_of_lines", "graphing_linear_relationships", "multiple_representations_of_linear_functions", "worksheet_grapher_a1_lin_mod_mult_rep", "equation_line_2", "connecting_slope_intercept_and_point_slope_forms", "equation_line_1", "equation_line_3", "worksheet_grapher_a1_mod_initial_plus_point", "worksheet_grapher_a1_mod_two_points", "analyzing_models_2step_rationals", "worksheet_grapher_a1_slope_intercept_integer", "worksheet_grapher_a1_slope_intercept_decimal", "modeling_linear_equations_in_standard_form", "graph_setup_linear_equation-1", "graph_setup_linear_equation-2", "introduction_to_functions", "graphs_of_functions", "classifying_relations_and_functions", "graphs_of_functions-1", "estimating_lines_of_best_fit", "using_lines_of_best_fit", "categorical_tables_frequency_tabulation_intro", "categorical_tables_frequency_analysis_intro", "categorical_tables_relative_frequency_tabulation_intro", "categorical_tables_relative_frequency_analysis_intro"],
    "course3_module3": ["exploring_two_step_equations", "solving_multi_step_equations", "solve_linear_equation_similar_terms_constant_integer_notype", "solve_linear_equation_similar_terms_constant_integer_type", "solve_linear_equation_similar_terms_constant_decimal_notype", "solve_linear_equation_similar_terms_constant_decimal_type", "analyzing_models_distributive", "worksheet_grapher_a1_linear_models_distrib_int", "worksheet_grapher_a1_linear_models_distrib_frac", "worksheet_grapher_a1_linear_models_distrib_div", "solve_linear_equation_distrib_mult", "solve_linear_equation_distrib_div", "solve_linear_equation_both_sides_notype", "solve_linear_equation_both_sides", "solving_equations_with_one_solution_infinite_and_no_solutions", "sorting_solutions", "introduction_to_systems_of_linear_equations", "worksheet_grapher_a1_linear_systems_int", "worksheet_grapher_a1_linear_systems_dec", "linear_system_solving_1"],
    "course3_module4": ["approximating_square_roots", "rational_irrational_1", "rational_irrational_ordering", "exploring_the_pythagorean_theorem", "applying_pythagorean_theorem", "problem_solving_using_the_pythagorean_theorem", "calculating_distances_on_the_coordinate_plane"],
    "course3_module5": ["introduction_to_the_power_rules", "simplify_exponents_1_prod_quot", "simplify_exponents_2_power", "simplify_exponents_3_prod_quot_power", "simplify_exponents_4_pos_mix", "simplify_exponents_5_neg_exp", "scientific_notation", "comparing_numbers_using_scientific_notation", "relating_volumes_of_cylinder_cones_and_spheres", "volume_surface_area_cylinder_vol", "volume_surface_area_cylinder_vol-_backward", "volume_surface_area_cone_vol", "volume_surface_area_cone_vol-_backward", "volume_surface_area_sphere_vol", "volume_surface_area_sphere_vol-_backward"]
}
workspaces = {
    "absolute_value_plot_equality": ["control", "empty-variant", "variant"],
    "absolute_value_solve_equality": ["empty-variant"],
    "adding_and_subtracting_decimals": ["empty-variant"],
    "adding_and_subtracting_integers": ["empty-variant"],
    "analyzing_different_forms_of_expressions": ["empty-variant"],
    "analyzing_distributions_with_shape_center_and_spread": ["empty-variant"],
    "analyzing_models_1step": ["empty-variant"],
    "analyzing_models_2step_integers": ["empty-variant"],
    "analyzing_models_2step_rationals": ["empty-variant"],
    "analyzing_models_distributive": ["empty-variant"],
    "analyzing_polynomial_functions": ["empty-variant"],
    "analyzing_residuals_of_lines_of_best_fit": ["empty-variant"],
    "analyzing_step_functions": ["empty-variant"],
    "angle_properties_calculating": ["empty-variant"],
    "angle_properties_justifying": ["empty-variant"],
    "angles_of_an_inscribed_quadrilateral": ["empty-variant"],
    "applying_pythagorean_theorem": ["empty-variant"],
    "approximating_square_roots": ["empty-variant"],
    "area_perimeter_circle_forwards": ["empty-variant"],
    "area_perimeter_composition": ["empty-variant"],
    "area_perimeter_mix_rectangle_derived": ["empty-variant"],
    "area_perimeter_mix_rectangular": ["empty-variant"],
    "binomial_theorem": ["empty-variant"],
    "building_absolute_value_functions": ["empty-variant"],
    "calculating_and_interpreting_average_rate_of_change": ["empty-variant"],
    "calculating_angles": ["empty-variant"],
    "calculating_angles_formed_by_a_transversal": ["empty-variant"],
    "calculating_compound_probabilities": ["empty-variant"],
    "calculating_distances_on_the_coordinate_plane": ["empty-variant"],
    "calculating_mean_absolute_deviation": ["empty-variant"],
    "calculating_the_area_of_a_sector": ["empty-variant"],
    "categorical_tables_conditional_frequency_analysis": ["empty-variant"],
    "categorical_tables_conditional_frequency_tabulation": ["empty-variant"],
    "categorical_tables_frequency_analysis": ["empty-variant"],
    "categorical_tables_frequency_analysis_intro": ["empty-variant"],
    "categorical_tables_frequency_tabulation": ["empty-variant"],
    "categorical_tables_frequency_tabulation_intro": ["empty-variant"],
    "categorical_tables_relative_frequency_analysis": ["empty-variant"],
    "categorical_tables_relative_frequency_analysis_intro": ["empty-variant"],
    "categorical_tables_relative_frequency_tabulation": ["empty-variant"],
    "categorical_tables_relative_frequency_tabulation_intro": ["empty-variant"],
    "choosing_appropriate_measures": ["empty-variant"],
    "choosing_trig_functions": ["empty-variant"],
    "classify_and_determine_angles": ["empty-variant"],
    "classify_polynomials": ["empty-variant"],
    "classifying_angles_formed_by_a_transversal": ["empty-variant"],
    "classifying_relations_and_functions": ["empty-variant"],
    "common_base_exponentials_contextual": ["empty-variant"],
    "commutative_and_associative_properties": ["empty-variant"],
    "compare_functions_diff_reps_exponential": ["empty-variant"],
    "compare_functions_diff_reps_linear": ["empty-variant"],
    "compare_functions_diff_reps_polynomial": ["empty-variant"],
    "compare_functions_diff_reps_quadratic": ["empty-variant"],
    "comparing_and_interpreting_center_and_spread": ["empty-variant"],
    "comparing_characteristics_of_data_displays": ["empty-variant"],
    "comparing_familiar_function_representations": ["empty-variant"],
    "comparing_numbers_using_scientific_notation": ["empty-variant"],
    "comparing_populations_using_data_displays": ["empty-variant"],
    "comparing_theoretical_and_experimental_probabilities": ["empty-variant"],
    "completing_the_square": ["empty-variant"],
    "compound_probability": ["empty-variant"],
    "conceptual_equations_2step_1var": ["empty-variant"],
    "conditional_probability": ["empty-variant"],
    "connecting_slope_intercept_and_point_slope_forms": ["empty-variant"],
    "constructing_box_and_whisker_plots": ["empty-variant"],
    "convert_frac_dec_equivalent": ["empty-variant"],
    "converting_between_systems": ["empty-variant"],
    "converting_quadratics_to_factored_form": ["empty-variant"],
    "converting_quadratics_to_general_form": ["empty-variant"],
    "converting_quadratics_to_vertex_form": ["empty-variant"],
    "converting_rational_numbers_to_decimals": ["empty-variant"],
    "converting_with_fractional_percents": ["empty-variant"],
    "converting_within_a_system": ["empty-variant"],
    "creating_and_interpreting_dot_plots": ["empty-variant"],
    "creating_and_interpreting_histograms": ["empty-variant"],
    "creating_and_interpreting_stem_plots": ["empty-variant"],
    "creating_three_dimensional_shapes_from_two_dimensional_figures": ["empty-variant"],
    "critical_attributes_of_similar_figures": ["empty-variant"],
    "data_displays_constructing_relative_frequency_histograms": ["empty-variant"],
    "decimal_ops_patterns": ["empty-variant"],
    "decimal_ops_problem_solving": ["empty-variant"],
    "decimal_ops_products": ["empty-variant"],
    "decimal_ops_sums_and_differences": ["empty-variant"],
    "decimal_ops_whole_number_and_decimal_quotients": ["empty-variant"],
    "defining_similarity": ["empty-variant"],
    "deriving_the_distance_formula": ["empty-variant"],
    "deriving_the_equation_of_a_circle": ["empty-variant"],
    "deriving_the_quadratic_formula": ["empty-variant"],
    "describing_rigid_motions_using_coordinates": ["empty-variant"],
    "describing_transformations_using_coordinates": ["empty-variant"],
    "determining_a_part": ["empty-variant"],
    "determining_a_whole": ["empty-variant"],
    "determining_central_and_inscribed_angles_in_circles": ["empty-variant"],
    "determining_characteristics_of_direct_variation_graphs": ["empty-variant"],
    "determining_chords_in_circles_in_circles": ["empty-variant"],
    "determining_interior_and_exterior_angles_in_circles": ["empty-variant"],
    "determining_probabilities": ["empty-variant"],
    "determining_surface_area_using_nets": ["empty-variant"],
    "determining_the_radius_and_center_of_a_circle": ["empty-variant"],
    "determining_the_value_of_an_independent_variable": ["empty-variant"],
    "determining_volume_using_unit_fraction_cubes": ["empty-variant"],
    "developing_algorithms_for_adding_and_subtracting_integers": ["empty-variant"],
    "developing_area_formulas": ["empty-variant"],
    "developing_definitions_of_rigid_motions": ["empty-variant"],
    "developing_the_fraction_division_algorithm": ["empty-variant"],
    "direct_variation_convert": ["empty-variant"],
    "direct_variation_equation": ["empty-variant"],
    "distance_midpoint_area_perimeter_": ["empty-variant"],
    "distance_midpoint_distance_formula_": ["empty-variant"],
    "distance_midpoint_intermediate_points_": ["empty-variant"],
    "distinguishing_between_populations_and_samples": ["empty-variant"],
    "dividing_decimals": ["empty-variant"],
    "drawing_polygons_on_the_coordinate_plane": ["empty-variant"],
    "equation_line_1": ["empty-variant"],
    "equation_line_2": ["empty-variant"],
    "equation_line_3": ["empty-variant"],
    "equation_line_parallel_perpendicular": ["empty-variant"],
    "equivalent_ratios": ["empty-variant"],
    "equivalent_ratios_rates_solving_double_numberline": ["empty-variant"],
    "equivalent_ratios_rates_solving_graph": ["empty-variant"],
    "equivalent_ratios_rates_solving_table": ["empty-variant", "fitted_skill_params"],
    "estimating_lines_of_best_fit": ["empty-variant"],
    "examining_the_shape_and_structure_of_functions": ["empty-variant"],
    "exploring_and_analyzing_patterns": ["empty-variant"],
    "exploring_decimal_facts": ["empty-variant"],
    "exploring_graphs_of_linear_functions": ["empty-variant"],
    "exploring_linear_inequalities": ["empty-variant"],
    "exploring_linear_regression": ["empty-variant"],
    "exploring_polynomial_regression": ["empty-variant"],
    "exploring_proportions_and_direct_variation": ["empty-variant"],
    "exploring_rigid_motions_and_dilations": ["empty-variant"],
    "exploring_symmetry_on_the_coordinate_plane": ["empty-variant"],
    "exploring_the_distributive_property_with_algebraic_expressions": ["empty-variant"],
    "exploring_the_distributive_property_with_numeric_expressions": ["empty-variant"],
    "exploring_the_pythagorean_theorem": ["empty-variant"],
    "exploring_two_step_equations": ["empty-variant"],
    "exponential_equations_solving_graphically": ["empty-variant"],
    "expression_evaluation_frac-dec-2": ["empty-variant"],
    "expression_evaluation_multiple_variables": ["empty-variant"],
    "expression_evaluation_one_step_int": ["empty-variant"],
    "expression_evaluation_two_step_int": ["empty-variant"],
    "factoring_expressions": ["empty-variant"],
    "factoring_higher_order_polynomials": ["empty-variant"],
    "finite_geometric_series": ["empty-variant"],
    "fraction_decimal_percent_conversions": ["empty-variant"],
    "fraction_division_model": ["empty-variant"],
    "fractional_percent_models": ["empty-variant"],
    "fractional_rates": ["empty-variant"],
    "function_transforms_linear_exponential_horizontal": ["empty-variant"],
    "function_transforms_linear_exponential_multiple": ["empty-variant"],
    "function_transforms_linear_exponential_reflectdilate": ["empty-variant"],
    "function_transforms_linear_exponential_table": ["empty-variant"],
    "function_transforms_linear_exponential_vertical": ["empty-variant"],
    "function_transforms_linear_quadratic_horizontal": ["empty-variant"],
    "function_transforms_linear_quadratic_multiple": ["empty-variant"],
    "function_transforms_linear_quadratic_reflectdilate": ["empty-variant"],
    "function_transforms_linear_quadratic_table": ["empty-variant"],
    "function_transforms_linear_quadratic_vertical": ["empty-variant"],
    "function_transforms_quadratic_review": ["empty-variant"],
    "functions_relations_addsubtract": ["empty-variant"],
    "functions_relations_calculate_inverses": ["empty-variant"],
    "functions_relations_evaluation": ["empty-variant"],
    "functions_relations_recognize_inverses": ["empty-variant"],
    "geo_transforms_di": ["empty-variant"],
    "geo_transforms_mix_multiple": ["empty-variant"],
    "geo_transforms_mix_single": ["empty-variant"],
    "geo_transforms_re": ["empty-variant"],
    "geo_transforms_ro": ["empty-variant"],
    "geo_transforms_sequences": ["empty-variant"],
    "geo_transforms_tr": ["empty-variant"],
    "graph_setup_linear_equation-1": ["empty-variant", "fitted_skill_params"],
    "graph_setup_linear_equation-2": ["empty-variant"],
    "graph_setup_linear_inequalities-1": ["empty-variant"],
    "graph_setup_linear_systems-1": ["empty-variant"],
    "graphing_linear_relationships": ["empty-variant"],
    "graphing_square_root_functions": ["empty-variant"],
    "graphs_of_equations": ["empty-variant"],
    "graphs_of_functions": ["empty-variant"],
    "graphs_of_functions-1": ["empty-variant"],
    "graphs_of_inverses": ["empty-variant"],
    "identifying_and_interpreting_ordered_pairs": ["empty-variant"],
    "identifying_greatest_common_factors_and_least_common_multiples": ["empty-variant"],
    "identifying_parts_of_complex_algebraic_expressions": ["empty-variant"],
    "identifying_parts_of_simple_algebraic_expressions": ["empty-variant"],
    "identifying_properties_of_quadratic_functions": ["empty-variant"],
    "identifying_quantities": ["empty-variant"],
    "identifying_signs_of_starting_values_and_rates": ["empty-variant"],
    "identifying_zeros_of_polynomials": ["empty-variant"],
    "independent_events": ["empty-variant"],
    "integer_add_subtract_nl_mix": ["empty-variant"],
    "interpreting_box_and_whisker_plots": ["empty-variant"],
    "interpreting_key_features_of_graphs_in_terms_of_quantities": ["empty-variant"],
    "interpreting_lines_of_best_fit": ["empty-variant"],
    "interpreting_piecewise_functions": ["empty-variant"],
    "introducing_negative_numbers": ["empty-variant"],
    "introduction_to_circles": ["empty-variant"],
    "introduction_to_complex_numbers": ["empty-variant"],
    "introduction_to_compound_events": ["empty-variant"],
    "introduction_to_exponential_functions": ["empty-variant"],
    "introduction_to_finite_geometric_series": ["empty-variant"],
    "introduction_to_function_families": ["empty-variant"],
    "introduction_to_functions": ["empty-variant"],
    "introduction_to_logarithmic_functions": ["empty-variant"],
    "introduction_to_parallel_and_perpendicular_lines": ["empty-variant"],
    "introduction_to_piecewise_functions": ["empty-variant"],
    "introduction_to_polynomial_arithmetic": ["empty-variant"],
    "introduction_to_proofs": ["empty-variant"],
    "introduction_to_rational_functions": ["empty-variant"],
    "introduction_to_special_right_triangles": ["empty-variant"],
    "introduction_to_systems_of_linear_equations": ["empty-variant"],
    "introduction_to_the_power_rules": ["empty-variant"],
    "introduction_to_transforming_exponential_functions": ["empty-variant"],
    "introduction_to_triangle_congruence": ["empty-variant"],
    "introduction_to_triangle_sum_and_exterior_angle_theorems": ["empty-variant"],
    "introduction_to_trigonometric_ratios": ["empty-variant"],
    "investigating_circles": ["empty-variant"],
    "investigating_inverses_of_functions": ["empty-variant"],
    "key_characteristics_polynomials": ["empty-variant"],
    "linear_inequalities_numberline": ["empty-variant"],
    "linear_inequalities_numberline_noneg": ["empty-variant"],
    "linear_inequalities_solver_1step": ["empty-variant"],
    "linear_inequalities_solver_2step": ["empty-variant"],
    "linear_inequalities_solver_both_sides": ["empty-variant"],
    "linear_relations_1": ["empty-variant"],
    "linear_system_solving_1": ["empty-variant"],
    "linear_system_solving_2": ["empty-variant"],
    "linear_system_solving_3": ["empty-variant"],
    "lines_cut_by_transversal_multiple": ["empty-variant"],
    "lines_cut_by_transversal_single": ["empty-variant"],
    "lines_rays_segments_angles_measuring": ["empty-variant"],
    "lines_rays_segments_angles_naming": ["empty-variant"],
    "making_sense_of_roots_and_zeros": ["empty-variant"],
    "maximizing_area": ["empty-variant"],
    "measures_central_tendency-1": ["empty-variant"],
    "measures_central_tendency-2": ["empty-variant", "fitted_skill_params"],
    "measures_central_tendency-2_intro": ["empty-variant", "fitted_skill_params"],
    "measures_central_tendency-3": ["empty-variant"],
    "modeling_equivalent_algebraic_expressions": ["empty-variant"],
    "modeling_linear_equations_in_standard_form": ["empty-variant"],
    "modeling_polynomial_functions": ["empty-variant"],
    "modeling_scenarios_with_equations": ["empty-variant"],
    "multiple_representations_of_linear_functions": ["empty-variant"],
    "multiple_representations_of_ratios": ["empty-variant"],
    "multiplying_and_dividing_integers": ["empty-variant"],
    "multiplying_decimals": ["empty-variant"],
    "normal_distribution_probability": ["empty-variant"],
    "normal_distribution_whole_zscore_percentiles": ["empty-variant"],
    "normal_distribution_zscore_percentiles": ["empty-variant"],
    "operating_with_functions_on_the_coordinate_plane": ["empty-variant"],
    "order_of_operations": ["empty-variant"],
    "partitioning_segments_in_given_ratios": ["empty-variant"],
    "pascal_s_triangle": ["empty-variant"],
    "percent_models": ["empty-variant"],
    "picture_algebra_addsub_total_given": ["empty-variant"],
    "picture_algebra_mix": ["empty-variant", "fitted_skill_params"],
    "picture_algebra_mix_variable": ["empty-variant", "fitted_skill_params"],
    "picture_algebra_multiply_total_given": ["empty-variant"],
    "piecewise_functions_linear_graph": ["empty-variant"],
    "piecewise_functions_linear_use": ["empty-variant"],
    "plotting_points": ["empty-variant"],
    "polynomial_multiplication_binomial_scaffolded": ["empty-variant"],
    "polynomial_multiplication_binomial_unscaffolded": ["empty-variant"],
    "polynomial_multiplication_poly_scaffolded": ["empty-variant"],
    "polynomial_multiplication_poly_unscaffolded": ["empty-variant"],
    "problem_solving_by_completing_the_square": ["empty-variant"],
    "problem_solving_by_factoring": ["empty-variant"],
    "problem_solving_using_the_pythagorean_theorem": ["empty-variant"],
    "proof_completing_measures": ["empty-variant"],
    "proof_connecting_steps": ["empty-variant"],
    "proof_parallelogram_theorems": ["empty-variant"],
    "proof_similar_triangles": ["empty-variant"],
    "proof_triangle_theorems_proving": ["empty-variant"],
    "proof_triangle_theorems_using": ["empty-variant"],
    "proof_using_congruent_tri": ["empty-variant"],
    "proofs_congruent_triangles_aas_asa": ["empty-variant"],
    "proofs_congruent_triangles_hl_ha": ["empty-variant"],
    "proofs_congruent_triangles_sas_sss": ["empty-variant"],
    "proofs_parallel_lines_converse_theorems": ["empty-variant"],
    "proofs_parallel_lines_theorems": ["empty-variant"],
    "properties_of_exponential_graphs": ["empty-variant"],
    "properties_of_parallelograms": ["empty-variant"],
    "properties_of_rational_exponents": ["empty-variant"],
    "proportional_relationships": ["empty-variant"],
    "proving_the_pythagorean_identity": ["empty-variant"],
    "pythag_diagram_special": ["empty-variant"],
    "quadratic_models_exponential_basic": ["empty-variant"],
    "quadratic_models_exponential_extended": ["empty-variant"],
    "quadratic_models_factored_monomial_binomial": ["empty-variant"],
    "quadratic_models_factored_review": ["empty-variant"],
    "quadratic_models_factored_two_binomials": ["empty-variant"],
    "quadratic_models_general_regression": ["empty-variant"],
    "quadratic_models_projectile_motion": ["empty-variant"],
    "quadratics_with_complex_roots": ["empty-variant"],
    "ratio_proportion_change3": ["empty-variant"],
    "ratio_proportion_change4": ["empty-variant"],
    "ratio_proportion_prop1": ["empty-variant"],
    "ratio_proportion_prop2": ["empty-variant"],
    "ratio_proportion_ratio2": ["empty-variant"],
    "rational_equations_1": ["empty-variant"],
    "rational_irrational_1": ["empty-variant"],
    "rational_irrational_ordering": ["empty-variant"],
    "rational_models_1": ["empty-variant"],
    "rational_models_2": ["empty-variant"],
    "rational_models_3": ["empty-variant"],
    "reasoning_about_absolute_value_inequalities": ["empty-variant"],
    "recognizing_concepts_of_conditional_probability": ["empty-variant"],
    "recognizing_growth_and_decay": ["empty-variant"],
    "recognizing_key_features_of_projectile_motion_graphs": ["empty-variant"],
    "recognizing_linear_and_exponential_models": ["empty-variant"],
    "reflectional_rotational_symmetry_reflectional": ["empty-variant"],
    "reflectional_rotational_symmetry_rotational": ["empty-variant"],
    "relating_arc_length_and_radius": ["empty-variant"],
    "relating_sines_and_cosines_of_complementary_angles": ["empty-variant"],
    "relating_the_domain_to_exponential_functions": ["empty-variant"],
    "relating_volumes_of_cylinder_cones_and_spheres": ["empty-variant"],
    "representing_compound_inequalities": ["empty-variant"],
    "representing_fraction_division": ["empty-variant"],
    "representing_integers_on_number_lines": ["empty-variant"],
    "representing_one_step_equations": ["empty-variant"],
    "representing_proportional_relationships_algebraically": ["empty-variant"],
    "representing_systems_of_linear_functions": ["empty-variant"],
    "rewriting_expressions_with_radical_and_rational_exponents": ["empty-variant"],
    "rewriting_proportions_as_products": ["empty-variant"],
    "right_triangle_trig_double": ["empty-variant"],
    "right_triangle_trig_single": ["empty-variant"],
    "rotations_and_reflections_on_the_plane": ["empty-variant"],
    "sales_tax_discounts_one_rate": ["empty-variant"],
    "sales_tax_discounts_two_rates": ["empty-variant"],
    "scale_drawings_3": ["empty-variant"],
    "scientific_notation": ["empty-variant"],
    "sequences_1": ["empty-variant"],
    "sequences_2": ["empty-variant"],
    "sequences_3": ["empty-variant"],
    "sequences_4_exponential_functions": ["empty-variant"],
    "sequences_4_linear_functions": ["empty-variant"],
    "similar_triangles": ["empty-variant"],
    "simple_probabilities": ["empty-variant"],
    "simplify_complex_numbers_addsub": ["empty-variant"],
    "simplify_complex_numbers_mult": ["empty-variant"],
    "simplify_complex_numbers_radicals": ["empty-variant"],
    "simplify_exponents_1_prod_quot": ["empty-variant"],
    "simplify_exponents_2_power": ["control", "empty-variant", "variant"],
    "simplify_exponents_3_prod_quot_power": ["empty-variant"],
    "simplify_exponents_4_pos_mix": ["empty-variant"],
    "simplify_exponents_5_neg_exp": ["empty-variant"],
    "simplify_exponents_6_neg_mix": ["empty-variant"],
    "simplify_order_of_ops_expression_numeric_contrast_addsub_multdiv": ["empty-variant"],
    "simplify_order_of_ops_expression_numeric_contrast_addsub_multdiv_intro": ["empty-variant"],
    "simplify_order_of_ops_expression_numeric_four_ops_complex_intro": ["empty-variant"],
    "simplify_order_of_ops_expression_numeric_mix_type_complex": ["empty-variant"],
    "simplify_order_of_ops_expression_numeric_mix_type_intro": ["empty-variant"],
    "simplify_order_of_ops_expression_numeric_mix_type_simple": ["empty-variant"],
    "simplify_order_of_ops_expression_numeric_parens_expon": ["empty-variant"],
    "simplify_order_of_ops_expression_numeric_parens_expon_intro": ["empty-variant"],
    "simplify_order_of_ops_expression_variable_complex": ["empty-variant"],
    "simplify_order_of_ops_expression_variable_contrast_addsub_multdiv": ["empty-variant"],
    "simplify_order_of_ops_expression_variable_contrast_addsub_multdiv_intro": ["empty-variant"],
    "simplify_order_of_ops_expression_variable_four_ops_complex": ["empty-variant"],
    "simplify_order_of_ops_expression_variable_four_ops_complex_intro": ["empty-variant"],
    "simplify_order_of_ops_expression_variable_mix_type": ["empty-variant"],
    "simplify_order_of_ops_expression_variable_mix_type_intro": ["empty-variant"],
    "simplify_order_of_ops_expression_variable_parens_expon": ["empty-variant"],
    "simplify_order_of_ops_expression_variable_parens_expon_intro": ["empty-variant"],
    "simplify_quadratic-1": ["empty-variant"],
    "simplify_quadratic-2": ["empty-variant"],
    "simplify_quadratic-3": ["empty-variant"],
    "simplify_quadratic-4": ["empty-variant"],
    "simplify_radical_1": ["empty-variant"],
    "simplify_radical_2_add": ["empty-variant"],
    "simplify_radical_3_mult": ["empty-variant"],
    "simplify_radical_4_div": ["empty-variant"],
    "simplify_radical_5_var": ["empty-variant"],
    "simplify_radical_add_subtract_variables": ["empty-variant"],
    "simplifying_numeric_expressions": ["empty-variant"],
    "simplifying_powers_of_i": ["empty-variant"],
    "simulating_compound_events": ["empty-variant"],
    "simulating_simple_events": ["empty-variant"],
    "sketching_polynomial_graphs_polys": ["empty-variant"],
    "sketching_polynomial_graphs_quads": ["empty-variant"],
    "solve_linear_equation_1step": ["empty-variant"],
    "solve_linear_equation_1step_add_subtract_notype": ["empty-variant"],
    "solve_linear_equation_1step_mult_div_notype": ["empty-variant"],
    "solve_linear_equation_2step": ["empty-variant"],
    "solve_linear_equation_2step_div_notype": ["empty-variant"],
    "solve_linear_equation_2step_div_typein": ["empty-variant"],
    "solve_linear_equation_2step_mult_notype": ["empty-variant"],
    "solve_linear_equation_2step_mult_typein": ["empty-variant"],
    "solve_linear_equation_both_sides": ["empty-variant"],
    "solve_linear_equation_both_sides_notype": ["empty-variant"],
    "solve_linear_equation_distrib_div": ["empty-variant"],
    "solve_linear_equation_distrib_mult": ["empty-variant"],
    "solve_linear_equation_similar_terms_constant_decimal_notype": ["empty-variant"],
    "solve_linear_equation_similar_terms_constant_decimal_type": ["empty-variant"],
    "solve_linear_equation_similar_terms_constant_integer_notype": ["empty-variant"],
    "solve_linear_equation_similar_terms_constant_integer_type": ["empty-variant"],
    "solve_literal_equation_side_by_side": ["empty-variant"],
    "solve_literal_equation_solo": ["empty-variant"],
    "solve_quadratic_equation_1": ["empty-variant"],
    "solve_quadratic_equation_factoring_1": ["empty-variant"],
    "solve_quadratic_equation_review": ["empty-variant"],
    "solver_add_subtract_poly_add_quad": ["empty-variant"],
    "solver_add_subtract_poly_subtract": ["empty-variant"],
    "solver_mixed_number_mult_div": ["empty-variant"],
    "solver_one_step_trig_equations_mix_notype": ["empty-variant"],
    "solver_one_step_trig_equations_sin_cos_notype": ["empty-variant"],
    "solver_one_step_trig_equations_tan_notype": ["empty-variant"],
    "solver_simplify_rational_add_subt": ["empty-variant"],
    "solver_simplify_rational_factor_cancel": ["empty-variant"],
    "solver_simplify_rational_mult_div": ["empty-variant"],
    "solving_any_base_equations": ["empty-variant"],
    "solving_area_problems": ["empty-variant"],
    "solving_base_e_equations": ["empty-variant"],
    "solving_base_two_ten_equations": ["empty-variant"],
    "solving_equations_with_one_solution_infinite_and_no_solutions": ["empty-variant"],
    "solving_multi_step_equations": ["empty-variant"],
    "solving_one_step_equations_with_a_balance": ["empty-variant"],
    "solving_polynomial_functions": ["empty-variant"],
    "solving_polynomial_inequalities": ["empty-variant"],
    "solving_simple_percent_problems": ["empty-variant"],
    "sorting_solutions": ["empty-variant"],
    "standard_deviation": ["empty-variant"],
    "synthetic_division": ["empty-variant"],
    "transforming_functions": ["empty-variant"],
    "understanding_average_rate_of_change_of_polynomial_functions": ["empty-variant"],
    "understanding_frequency_tables": ["empty-variant"],
    "understanding_linear_functions": ["empty-variant"],
    "understanding_opposites": ["empty-variant"],
    "understanding_parallelograms": ["empty-variant"],
    "understanding_ratio_relationships": ["empty-variant"],
    "understanding_similarity": ["empty-variant"],
    "understanding_the_slopes_of_lines": ["empty-variant"],
    "understanding_the_unit_circle": ["empty-variant"],
    "understanding_volume_of_right_prisms": ["empty-variant"],
    "using_absolute_value": ["empty-variant"],
    "using_angle_theorems": ["empty-variant"],
    "using_graphs_to_solve_equations": ["empty-variant"],
    "using_linear_regression": ["empty-variant"],
    "using_lines_of_best_fit": ["empty-variant"],
    "using_mean_absolute_deviation": ["empty-variant"],
    "using_proportions_to_solve_percent_problems": ["empty-variant"],
    "using_scale_drawings": ["empty-variant"],
    "using_substitution_to_determine_solutions": ["empty-variant"],
    "using_substitution_to_identify_solutions_to_inequalities": ["empty-variant"],
    "using_the_distributive_property_with_numeric_expressions": ["empty-variant"],
    "using_the_properties_of_exponents": ["empty-variant"],
    "using_the_pythagorean_identity": ["empty-variant"],
    "using_triangle_congruence": ["empty-variant"],
    "verifying_properties_of_rigid_motions": ["empty-variant"],
    "visualizing_cross_sections_of_three_dimensional_shapes": ["empty-variant"],
    "volume_surface_area_cone_vol": ["control", "empty-variant", "variant"],
    "volume_surface_area_cone_vol-_backward": ["empty-variant"],
    "volume_surface_area_cylinder_vol": ["empty-variant"],
    "volume_surface_area_cylinder_vol-_backward": ["empty-variant"],
    "volume_surface_area_right_prism_sa": ["empty-variant", "fitted_skill_params"],
    "volume_surface_area_right_prism_vol": ["empty-variant"],
    "volume_surface_area_right_prism_vol-_backward": ["empty-variant"],
    "volume_surface_area_sphere_vol": ["control", "empty-variant", "variant"],
    "volume_surface_area_sphere_vol-_backward": ["empty-variant"],
    "volume_surface_area_sq_pyramid_vol": ["empty-variant"],
    "volume_surface_area_sq_pyramid_vol-_backward": ["empty-variant"],
    "work_mixture_distance-1": ["empty-variant"],
    "work_mixture_distance-2": ["empty-variant"],
    "worksheet_grapher_a1_direct_variation": ["empty-variant"],
    "worksheet_grapher_a1_four_quadrant_graphing_1step": ["empty-variant"],
    "worksheet_grapher_a1_lin_mod_mult_rep": ["empty-variant", "fitted_skill_params"],
    "worksheet_grapher_a1_linear_models_distrib_div": ["empty-variant"],
    "worksheet_grapher_a1_linear_models_distrib_frac": ["empty-variant"],
    "worksheet_grapher_a1_linear_models_distrib_int": ["empty-variant"],
    "worksheet_grapher_a1_linear_systems_dec": ["empty-variant"],
    "worksheet_grapher_a1_linear_systems_int": ["empty-variant"],
    "worksheet_grapher_a1_mod_initial_plus_point": ["empty-variant"],
    "worksheet_grapher_a1_mod_two_points": ["empty-variant"],
    "worksheet_grapher_a1_patterns_1step_eqn_ops": ["empty-variant"],
    "worksheet_grapher_a1_patterns_1step_expr_ops": ["empty-variant"],
    "worksheet_grapher_a1_patterns_2step_expr": ["empty-variant"],
    "worksheet_grapher_a1_slope_intercept_decimal": ["empty-variant"],
    "worksheet_grapher_a1_slope_intercept_integer": ["empty-variant"],
    "worksheet_grapher_a1_solving_1step_dec": ["empty-variant"],
    "worksheet_grapher_a1_solving_1step_int": ["empty-variant"],
    "worksheet_grapher_a1_solving_2step_dec_frac": ["empty-variant"],
    "worksheet_grapher_a1_solving_2step_int": ["empty-variant"],
    "writing_an_expression_from_a_scenario_table_or_graph": ["empty-variant"],
    "writing_and_evaluating_exponent_expressions":    ["empty-variant"]
}