name: Auto Merge Dependabot PRs
on: 
  pull_request:
jobs:
  auto-merge-dependabot-prs:
    name: Auto Merge Dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.REPO_PAT }}
          target: major