name: Backend Deploy to Dev Environment
on:
  push:
    branches:
      - dev
    paths:
      - backend/**
  workflow_dispatch:
jobs:
  init:
    name: Dev Deploy Init
    runs-on: ubuntu-latest
    if: github.repository_owner == 'CarnegieLearningWeb'
    outputs:
      application_name: ${{ steps.get-env-vars.outputs.application_name }}
      environment_name: ${{ steps.get-env-vars.outputs.environment_name }}
      version: ${{ steps.get-dev-version.outputs.version }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Get Dev Version
        id: get-dev-version
        uses: ./.github/actions/get-dev-version
        with:
          dir: backend/packages/Upgrade
      - name: Load Env Vars
        uses: tw3lveparsecs/github-actions-setvars@v0.1
      - name: Get Env Vars
        id: get-env-vars
        run: |
          echo "::set-output name=application_name::$EB_DEV_APP_NAME"
          echo "::set-output name=environment_name::$EB_DEV_ENV_NAME"
  start-dev-deployment:
    uses: ./.github/workflows/backend-deploy.yml
    needs: init
    with:
      application_name: ${{ needs.init.outputs.application_name }}
      environment_name: ${{ needs.init.outputs.environment_name }}
      version: ${{ needs.init.outputs.version }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      token: ${{ secrets.GITHUB_TOKEN }}
