name: Backend Build and Deploy
on:
  repository_dispatch:
    types: [trigger-backend-build]
jobs:
  backend-build-and-deploy:
    name: Backend Build and Deploy Dev
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Get Package Version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
        id: package-version
        with:
          path: backend/packages/Upgrade
      - name: Generate Changelogs
        run: |
          echo 'SLACK_CHANGELOG<<EOF' >> $GITHUB_ENV
          git log --color=never --pretty='tformat:%xe2%x80%xa2 `%h` %s (%an)' ${{github.event.client_payload.before}}..${{github.event.client_payload.after}} >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo 'RELEASE_CHANGELOG<<EOF' >> $GITHUB_ENV
          git log --color=never --pretty=' - %h %s' ${{github.event.client_payload.before}}..${{github.event.client_payload.after}} >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/} 
      - name: Generate logs
        run: |
          echo 'dev eb env name: '
          echo ${{ secrets.EB_ENV_NAME }} | sed 's/./& /g'
          echo 'dev eb env url: '
          echo ${{ secrets.ENV_URL }}' | sed 's/./& /g'

  backend-build-and-deploy-bsnl:
    name: Backend Build and Deploy BSNL
    runs-on: ubuntu-latest
    environment: bsnl   
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Get Package Version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
        id: package-version
        with:
          path: backend/packages/Upgrade
      - name: Generate Changelogs
        run: |
          echo 'SLACK_CHANGELOG<<EOF' >> $GITHUB_ENV
          git log --color=never --pretty='tformat:%xe2%x80%xa2 `%h` %s (%an)' ${{github.event.client_payload.before}}..${{github.event.client_payload.after}} >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo 'RELEASE_CHANGELOG<<EOF' >> $GITHUB_ENV
          git log --color=never --pretty=' - %h %s' ${{github.event.client_payload.before}}..${{github.event.client_payload.after}} >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Generate logs
        run: |
          echo 'dev eb env name: '
          echo ${{ secrets.EB_ENV_NAME }} | sed 's/./& /g'
          echo 'dev eb env url: '
          echo ${{ secrets.ENV_URL }}' | sed 's/./& /g'