name: Backend Build and Deploy
on:
  repository_dispatch:
    types: [trigger-backend-build]
jobs:
  backend-build-and-deploy:
    name: Backend Build and Deploy
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with: 
          ref: ${{ github.event.client_payload.tag }}

      - uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Get Package Version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
        id: package-version
        with:
          path: backend/packages/Upgrade

#############################################  Build Steps #############################################

      - name: Build
        working-directory: backend
        run: |
          npm ci
          zip -qq -r upgrade-backend-v${{ steps.package-version.outputs.current-version}}.zip node_modules packages/Upgrade Dockerfile Dockerrun.aws.json package.json tsconfig.json tslint.json
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: backend/upgrade-backend-v${{ steps.package-version.outputs.current-version}}.zip
          tag: upgrade-backend-v${{ steps.package-version.outputs.current-version}}
          name: UpGrade Backend ${{ steps.package-version.outputs.current-version}}
          body: ${{ github.event.client_payload.release_changelog }}
          commit: main
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Trigger Deployment Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-backend-deployment
          client-payload: '{"tag": "${{ steps.lambda-version-bump.outputs.newTag }}"}'

      - name: Success Slack Message
        uses: aibexhq/slack-rich-notify@v2.0.1
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channel: ${{ secrets.SLACK_BUILD_CHANNEL }}
          message: |
            *<https://github.com/${{ github.event.repository.full_name }}/releases/tag/upgrade-backend-v${{ steps.package-version.outputs.current-version }}|UpGrade Backend ${{ steps.package-version.outputs.current-version }}> build was successful*
            ${{ github.event.client_payload.slack_changelog }}

      - name: Failure Slack Message
        uses: aibexhq/slack-rich-notify@v2.0.1
        if: failure()
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channel: ${{ secrets.SLACK_BUILD_CHANNEL }}
          message: |
            ${{ secrets.SLACK_FAILURE_PINGS}} *UpGrade Backend ${{ steps.package-version.outputs.current-version }} build FAILURE*
            <https://github.com/${{ github.event.repository.full_name }}/actions/runs/${{ github.run_id }}|Click here to view the full log>
            ${{ github.event.client_payload.slack_changelog }}

#############################################  Deploy Steps #############################################

      - name: Deploy to QA
        id: deploy-backend
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          version_label: ${{ steps.package-version.outputs.current-version}}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: backend/upgrade-backend-v${{ steps.package-version.outputs.current-version}}.zip

      - name: Success Deploy Message
        uses: aibexhq/slack-rich-notify@v2.0.1
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channel: ${{ secrets.SLACK_DEPLOY_CHANNEL }}
          message: |
            *<https://github.com/${{ github.event.repository.full_name }}/releases/tag/upgrade-backend-v${{ steps.package-version.outputs.current-version }}|UpGrade Backend ${{ steps.package-version.outputs.current-version }}>* has been deployed to the `staging` environment at ${{ secrets.DEV_URL}}
            ${{ github.event.client_payload.slack_changelog }}

      - name: Failure Deploy Message
        uses: aibexhq/slack-rich-notify@v2.0.1
        if: failure() && steps.deploy-backend.outcome == 'failure'
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channel: ${{ secrets.SLACK_DEPLOY_CHANNEL }}
          message: |
            ${{ secrets.SLACK_FAILURE_PINGS}} *<https://github.com/${{ github.event.repository.full_name }}/releases/tag/upgrade-backend-v${{ steps.package-version.outputs.current-version }}|UpGrade Backend ${{ steps.package-version.outputs.current-version }}> deployment FAILURE*
            <https://github.com/${{ github.event.repository.full_name }}/actions/runs/${{ github.run_id }}|Click here to view the full log>
            ${{ github.event.client_payload.slack_changelog }}