name: Backend Build and Deploy
on:
  repository_dispatch:
    types: [trigger-backend-build]
jobs:
  backend-build-and-deploy-dev:
    name: Backend Build and Deploy dev
    # if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
        
      - name: Generate logs
        run: |
          echo 'dev eb env name: ${{ secrets.EB_ENV_NAME }}'
          echo 'dev eb env url: ${{ secrets.ENV_URL }}'
  
  backend-build-and-deploy-bsnl:
    name: Backend Build and Deploy bsnl
    # if: github.ref == 'refs/heads/bsnl'
    runs-on: ubuntu-latest
    environment: bsnl
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
        
      - name: Generate logs
        run: |
          echo 'bsnl eb env name: ${{ secrets.EB_ENV_NAME }}'
          echo 'bsnl eb env url: ${{ secrets.ENV_URL }}'
