name: 'Build and Deploy'
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - projects/server/**
      - terraform/**
jobs:
  bump-version:
    name: 'Build and Deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: phips28/gh-action-bump-version@v8.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm ci
      - run: npm run build:prod
      - run: zip -r upgrade-client-v${{ steps.package-version.outputs.current-version}}.zip *
        working-directory: dist/abtesting
      - run: mv dist/abtesting/upgrade-client-v${{ steps.package-version.outputs.current-version}}.zip .
      - name: Generate Release Changelog
        uses: Bullrich/generate-release-changelog@2.0.1
        id: changelog
        env:
          REPO: ${{ github.repository }}
      - name: Generate Slack Changelog
        run: |
          echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
          git log --color=never --pretty='tformat:%xe2%x80%xa2 `%h` %s (%an)' ${{github.event.before}}..HEAD >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - uses: martinbeentjes/npm-get-version-action@v1.1.0
        id: package-version
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: upgrade-client-v${{ steps.package-version.outputs.current-version}}.zip
          tag: v${{ steps.package-version.outputs.current-version}}
          name: Upgrade Client ${{ steps.package-version.outputs.current-version}}
          body: ${{ steps.changelog.outputs.changelog }}
          commit: master
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: shallwefootball/s3-upload-action@v1.1.2
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.S3_BUCKET }}
          source_dir: dist/abtesting/