name: UpGrade Client Libs JS Publish
on:
  push:
    branches:
      - main
    paths:
      - clientlibs/js/**
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag ref to publish'
        required: true
        default: 'main'  

permissions:
  id-token: write
  contents: read

jobs:
  clientlibs-js-publish:
    name: UpGrade Client Libs JS Publish
        run: |
          echo "::set-output name=ref::${{ inputs.ref || github.event.inputs.ref }}"
      - name: Git Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ steps.set-vars.outputs.ref }}
      - name: Build Types Package
        uses: ./.github/actions/generic-npm-build
        with:
          working_directory: clientlibs/js
      - name: Publish Client Libs js Package
        run: npm publish
        working-directory: clientlibs/js/package.json
