# The following secrets need to be set for the deployment to work
#  AWS_ACCESS_KEY_ID
#  AWS_SECRET_ACCESS_KEY
#  AWS_REGION
#  S3_BUCKET
#  EB_APP_NAME
#  EB_ENV_NAME
#  SLACK_TOKEN
#  SLACK_BUILD_CHANNEL
#  SLACK_DEPLOY_CHANNEL

# Optional secrets
#  SLACK_FAILURE_PINGS

name: Create Release And Deploy
on:
  push:
    branches:
      - master
    paths:
      - .github/**
      - packages/Upgrade/**
      - Docker*
      - package*.json
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: phips28/gh-action-bump-version@v8.0.7
        with:
          tag-prefix: upgrade-backend-
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: packages/Upgrade
      - uses: martinbeentjes/npm-get-version-action@v1.1.0
        id: package-version
        with:
          path: packages/Upgrade
      - name: Generate Release Changelog
        uses: Bullrich/generate-release-changelog@2.0.1
        id: changelog
        env:
          REPO: ${{ github.repository }}
      - name: Generate Slack Changelog
        run: |
          echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
          git log --color=never --pretty='tformat:%xe2%x80%xa2 `%h` %s (%an)' ${{github.event.before}}..HEAD >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - run: npm install
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r upgrade-backend-v${{ steps.package-version.outputs.current-version}}.zip node_modules packages/Upgrade Dockerfile Dockerrun.aws.json package.json tsconfig.json tslint.json
      - uses: ncipollo/release-action@v1
        with:
          artifacts: upgrade-backend-v${{ steps.package-version.outputs.current-version}}.zip
          tag: upgrade-backend-v${{ steps.package-version.outputs.current-version}}
          name: UpGrade Backend ${{ steps.package-version.outputs.current-version}}
          body: ${{ steps.changelog.outputs.changelog }}
          commit: master
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Success Build Message
        uses: aibexhq/slack-rich-notify@v2.0.1
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channel: ${{ secrets.SLACK_BUILD_CHANNEL }}
          message: |
            *<https://github.com/${{ github.event.repository.full_name }}/releases/tag/v${{ steps.package-version.outputs.current-version }}|UpGrade Backend ${{ steps.package-version.outputs.current-version }}> build was successful*
            {{ env.CHANGELOG }}
      - name: Failure Build Message
        uses: aibexhq/slack-rich-notify@v2.0.1
        if: failure()
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channel: ${{ secrets.SLACK_BUILD_CHANNEL }}
          message: |
            ${{ secrets.SLACK_FAILURE_PINGS}} *<https://github.com/${{ github.event.repository.full_name }}/releases/tag/v${{ steps.package-version.outputs.current-version }}|UpGrade Backend ${{ steps.package-version.outputs.current-version }}> build FAILURE*
            {{ env.CHANGELOG }}
      - name: Deploy to QA
        id: deploy
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          version_label: ${{ steps.package-version.outputs.current-version}}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: upgrade-backend-v${{ steps.package-version.outputs.current-version}}.zip
      - name: Success Deploy Message
        uses: aibexhq/slack-rich-notify@v2.0.1
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channel: ${{ secrets.SLACK_DEPLOY_CHANNEL }}
          message: |
            *<https://github.com/${{ github.event.repository.full_name }}/releases/tag/v${{ steps.package-version.outputs.current-version }}|UpGrade Backend ${{ steps.package-version.outputs.current-version }}> has been deployed to https://upgradeapi.qa-cli.net/api*
            {{ env.CHANGELOG }}
      - name: Failure Deploy Message
        uses: aibexhq/slack-rich-notify@v2.0.1
        if: failure() && steps.deploy.outcome == 'failure'
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channel: ${{ secrets.SLACK_DEPLOY_CHANNEL }}
          message: |
            ${{ secrets.SLACK_FAILURE_PINGS}} *<https://github.com/${{ github.event.repository.full_name }}/releases/tag/v${{ steps.package-version.outputs.current-version }}|UpGrade Backend ${{ steps.package-version.outputs.current-version }}> deployment FAILURE*
            {{ env.CHANGELOG }}