name: Create Release
on:
  workflow_call:
  workflow_dispatch:
jobs:
  check-if-already-released:
    name: Check if Already Released
    runs-on: ubuntu-latest
    outputs:
      already-released: ${{ steps.check-if-already-released.outputs.result }}
    steps:
      - id: check-if-already-released
        uses: actions/github-script@v6
        with:
          script: |
            const repo = "${{ github.repository }}".split("/").pop()
            const tags = await github.paginate(
              github.rest.repos.listTags, 
              {owner: "${{ github.repository_owner }}", repo: repo}
            );
            console.log(tags)
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: "${{ github.repository_owner }}",
              repo: repo
            });
            const branch = await github.rest.repos.getBranch({
              owner: "${{ github.repository_owner }}",
              repo: repo,
              branch: "${{ github.ref }}"
            });
            const result = tags.find(element => element.name === latestRelease.data.tag_name).commit.sha === branch.data.commit.sha;
            console.log(result);
            return result;
      
  create-release:
    name: Create Release
    needs: check-if-already-released
    if: needs.check-if-already-released.outputs.already-released == 'false'
    runs-on: ubuntu-latest
    outputs:
      application_name: ${{ steps.get-env-vars.outputs.application_name }}
      environment_name: ${{ steps.get-env-vars.outputs.environment_name }}
      function_name: ${{ steps.get-env-vars.outputs.function_name }}
      s3_bucket: ${{ steps.get-env-vars.outputs.s3_bucket }}
      version: ${{ steps.get-version.outputs.result }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install semver
      - name: Load Env Vars
        uses: tw3lveparsecs/github-actions-setvars@v0.1
      - name: Get Env Vars
        id: get-env-vars
        run: |
          echo "::set-output name=application_name::$EB_STAGING_APP_NAME"
          echo "::set-output name=environment_name::$EB_STAGING_ENV_NAME"
          echo "::set-output name=s3_bucket::$STAGING_S3_BUCKET"
          echo "::set-output name=function_name::$STAGING_LAMBDA_FUNCTION_NAME"
      - id: get-version
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            var semver = require('semver');
            const tagNames = await github.paginate(
              github.rest.repos.listTags, 
              {owner: "${{ github.repository_owner }}", repo: "UpGrade"},
              (response) => response.data.map((tag) => tag.name)
            );
            const tags = tagNames.filter(tag => tag.startsWith("${{ steps.get-version.outputs.version }}."));
            const result = tags.length ? semver.inc(tags.sort(semver.rcompare)[0], 'patch') : "${{ steps.get-version.outputs.version }}.0"
            console.log(result);
            return result;
      - name: Set Backend App Version
        working-directory: backend/packages/Upgrade
        run: npm version ${{ steps.get-version.outputs.result }} --git-tag-version=false
      - name: Package Backend
        working-directory: backend
        run: |
          npm version ${{ steps.get-version.outputs.result }} --git-tag-version=false
          cp -R ../types packages/Upgrade
          npm ci
          zip -qq -r upgrade-backend-${{ steps.get-version.outputs.result }}.zip node_modules packages/Upgrade Dockerfile Dockerrun.aws.json package.json tsconfig.json tslint.json
          mv upgrade-backend-${{ steps.get-version.outputs.result }}.zip ../
      - name: Build Frontend
        working-directory: frontend
        run: |
          npm version ${{ steps.get-version.outputs.result }} --git-tag-version=false
          npm ci
          npm run build:prod
      - name: Package Frontend
        working-directory: frontend/dist/upgrade
        run: |
          zip -r upgrade-frontend-${{ steps.get-version.outputs.result }}.zip *
          mv upgrade-frontend-${{ steps.get-version.outputs.result }}.zip ../../..
      - name: Build Lambda
        working-directory: backend/packages/Schedular
        run: |
          npm version ${{ steps.get-version.outputs.result }} --git-tag-version=false
          npm ci
          npm run build
          mkdir lib
          cp -a node_modules/ lib/node_modules
          cp -a dist/schedule lib/schedule
      - name: Package Lambda
        working-directory: backend/packages/Schedular/lib
        id: package-lambda
        run: |
          zip -r upgrade-lambda-${{ steps.get-version.outputs.result }}.zip *
          mv upgrade-lambda-${{ steps.get-version.outputs.result }}.zip ../../../..
      - uses: ncipollo/release-action@v1
        with:
          artifacts: upgrade-*.zip
          commit: main
          generateReleaseNotes: true
          tag: ${{ steps.get-version.outputs.result }}
          token: ${{ secrets.GITHUB_TOKEN }}
  deploy-backend-staging:
    name: Deploy Backend to Staging
    uses: ./.github/workflows/backend-deploy.yml
    needs: [create-release, check-if-already-released]
    if: needs.check-if-already-released.outputs.already-released == 'false' && github.repository_owner == 'CarnegieLearningWeb'
    with:
      application_name: ${{ needs.create-release.outputs.application_name }}
      environment_name: ${{ needs.create-release.outputs.environment_name }}
      version: ${{ needs.create-release.outputs.version }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      token: ${{ secrets.GITHUB_TOKEN }}
  deploy-frontend-staging:
    name: Deploy Frontend to Staging
    uses: ./.github/workflows/frontend-deploy.yml
    needs: [create-release, check-if-already-released]
    if: needs.check-if-already-released.outputs.already-released == 'false' && github.repository_owner == 'CarnegieLearningWeb'
    with:
      s3_bucket: ${{ needs.create-release.outputs.s3_bucket }}
      version: ${{ needs.create-release.outputs.version }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      token: ${{ secrets.GITHUB_TOKEN }}
  deploy-lambda-staging:
    name: Deploy Lambda to Staging
    uses: ./.github/workflows/lambda-deploy.yml
    needs: [create-release, check-if-already-released]
    if: needs.check-if-already-released.outputs.already-released == 'false' && github.repository_owner == 'CarnegieLearningWeb'
    with:
      function_name: ${{ needs.create-release.outputs.function_name }}
      version: ${{ needs.create-release.outputs.version }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      token: ${{ secrets.GITHUB_TOKEN }}
