name: Frontend Deploy
on:
  workflow_call:
    inputs:
      s3_bucket:
        required: true
        type: string
      version:
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
  workflow_dispatch:
    inputs:
      s3_bucket:
        description: S3 Bucket to deploy frontend code to
        required: true
        type: string
      version:
        description: Version of frontend being deployed
        required: false
        type: string
jobs:
  frontend-deploy:
    name: Frontend Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag exists
        id: check-tag
        uses: mukunku/tag-exists-action@v1.0.0
        with:
          tag: ${{ inputs.version }}

        # If the tag already exists, just download the artifact from that release
      - name: Download Release Artifact
        if: steps.check-tag.outputs.exists = 'true'
        uses: robinraju/release-downloader@v1.3
        with:
          repository: CarnegieLearningWeb/UpGrade
          tag: ${{ inputs.version }}
          fileName: upgrade-frontend-${{ inputs.version }}.zip
      - name: Unpack Release Artifact
        if: steps.check-tag.outputs.exists = 'true'
        working-directory: frontend
        run: |
          mkdir -p dist/upgrade
          unzip ../upgrade-frontend-${{ inputs.version }}.zip -d dist/upgrade

      # Otherwise, build the artifact
      - name: Git Checkout
        if: steps.check-tag.outputs.exists = 'false'
        uses: actions/checkout@v2
      - name: Frontend Build
        if: steps.check-tag.outputs.exists = 'false'
        uses: ./.github/actions/generic-npm-build
        with:
          working_directory: frontend
          build_script: build:prod
          version: ${{ inputs.version }}
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ inputs.s3_bucket }}
          SOURCE_DIR: frontend/dist/upgrade