name: Frontend Deploy to Dev Environment
on:
  push:
    branches:
      - dev
    paths:
      - frontend/**
  workflow_dispatch:
jobs:
  frontend-deploy-dev:
    name: Frontend Deploy to Dev Environment
    runs-on: ubuntu-latest
    if: github.repository_owner == 'CarnegieLearningWeb'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Get Dev Version
        id: get-dev-version
        uses: ./.github/actions/get-dev-version
        with:
          dir: frontend
      - uses: ./.github/workflows/frontend-deploy.yml
        with:
          s3_bucket: ${{ env.DEV_S3_BUCKET }}
          version: ${{ steps.get-dev-version.outputs.version }}