name: Types Build
on: ['pull_request', 'workflow_dispatch']
jobs:
  types-build:
    name: Types Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Build Types
        uses: ./.github/actions/generic-npm-build
        with:
          working_directory: types