name: UpGrade Types Publish
on:
  push:
    branches:
      - main
    paths:
      - types/**
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag ref to publish'
        required: true
        default: 'main'
jobs:
  types-publish:
    name: UpGrade Types Publish
    runs-on: ubuntu-latest
    steps:
      - name: Set Input Variables
        id: set-vars
        run: |
          echo "::set-output name=ref::${{ inputs.ref || github.event.inputs.ref }}"
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.set-vars.outputs.ref }}
      - name: Build Types Package
        uses: ./.github/actions/generic-npm-build
        with:
          working_directory: types
      - name: Publish Types Package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: types/package.json