name: Clientlibs-js Build and Publish
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'backend/**'
      - 'clientlibs/**'
      - 'frontend/**'
      - '**/*ignore'
      - '**/README.md'
      - '**/terraform/**'
      - '**/LICENCE'
      - '**/.prettier*'
      - '**/locust/**'
      - '**/.editoreconfig'
      - '.github/**'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'CarnegieLearningWeb'
    defaults:
      run:
        working-directory: types
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: types/package.json