name: Version Bump
on: workflow_dispatch
jobs:
  version-bump:
    name: Version Bump
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Main Version Bump
        run: npm version patch --git-tag-version=false
      - name: Get New Version
        id: get-version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "::set-output name=version::$VERSION"
      - name: Backend Version Bump
        working-directory: backend
        run: npm version ${{ steps.get-version.outputs.version }} --git-tag-version=false
      - name: Backend App Version Bump
        working-directory: backend/packages/Upgrade
        run: npm version ${{ steps.get-version.outputs.version }} --git-tag-version=false
      - name: Lambda App Version Bump
        working-directory: backend/packages/Schedular
        run: npm version ${{ steps.get-version.outputs.version }} --git-tag-version=false
      - name: Frontend Version Bump
        working-directory: frontend
        run: npm version ${{ steps.get-version.outputs.version }} --git-tag-version=false
      - id: create-pr
        uses: repo-sync/pull-request@v2
        with:
          branch: version-bump-${{ steps.get-version.outputs.version }}
          destination_branch: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated Version Bump: ${{ steps.get-version.outputs.version }}"
      - name: Approve PR
        uses: actions/github-script@v6
        with:
          script: |
            await github.pulls.createReview({
              owner: "${{ github.repository_owner }}",
              repo: "UpGrade",
              pull_number: ${{ steps.create-pr.outputs.pr_number }},
              event: "APPROVE"
            })
      - name: Enable PR auto merge
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.REPO_PAT }}
          pull-request-number:
            ${{ steps.create-pr.outputs.pr_number }}
          merge-method: merge
