name: Version Bump
on: workflow_dispatch
jobs:
  version-bump:
    name: Version Bump
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Main Version Bump
        run: npm version patch
      - name: Get New Version
        id: get-version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "::set-output name=version::$VERSION"
      - name: Backend Version Bump
        working-directory: backend
        run: npm version ${{ steps.get-version.outputs.version }}
      - name: Backend App Version Bump
        working-directory: backend/packages/Upgrade
        run: npm version ${{ steps.get-version.outputs.version }}
      - name: Lambda App Version Bump
        working-directory: backend/packages/Schedular
        run: npm version ${{ steps.get-version.outputs.version }}
      - name: Frontend Version Bump
        working-directory: frontend
        run: npm version ${{ steps.get-version.outputs.version }}
      - name: Commit Changes
        run: |
          git config --global user.name "Automated Version Bump"
          git config --global user.email "gh-action-bump-version@users.noreply.github.com"
          git commit -am "Automated version bump to ${{ steps.get-version.outputs.version }}"
          git push
  trigger-merge-to-main:
    name: Trigger Merge to Main
    uses: ./.github/workflows/merge-dev-to-main.yml
    needs: version-bump
